import { type NextRequest, NextResponse } from "next/server"
import type { PropertyFilter } from "@/lib/models/property"

// Sample data for all 50 states + DC
const sampleProperties = [
  // Alabama
  {
    id: "prop_alabama_1",
    address: "123 Historic Mansion Drive",
    city: "Birmingham",
    state: "AL",
    zipCode: "35203",
    value: 2800000,
    propertyType: "mansion",
    ownerName: "Southern Heritage Trust",
    ownerType: "trust",
    ownerWealth: 45000000,
    coordinates: { lat: 33.5186, lng: -86.8104 },
    bedrooms: 6,
    bathrooms: 5,
    sqft: 8500,
    yearBuilt: 1895,
    images: ["/placeholder.svg?height=300&width=400&text=Alabama+Mansion"],
    features: ["Historic", "Pool", "Gardens"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Alaska
  {
    id: "prop_alaska_1",
    address: "456 Wilderness Lodge Road",
    city: "Anchorage",
    state: "AK",
    zipCode: "99501",
    value: 4500000,
    propertyType: "lodge",
    ownerName: "Arctic Holdings Corp",
    ownerType: "corporation",
    ownerWealth: 85000000,
    coordinates: { lat: 61.2181, lng: -149.9003 },
    bedrooms: 8,
    bathrooms: 6,
    sqft: 12000,
    yearBuilt: 2015,
    images: ["/placeholder.svg?height=300&width=400&text=Alaska+Lodge"],
    features: ["Mountain Views", "Fireplace", "Ski Access"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Arizona
  {
    id: "prop_arizona_1",
    address: "789 Desert Mountain Estate",
    city: "Scottsdale",
    state: "AZ",
    zipCode: "85260",
    value: 7200000,
    propertyType: "estate",
    ownerName: "Desert Luxury Holdings",
    ownerType: "llc",
    ownerWealth: 125000000,
    coordinates: { lat: 33.4942, lng: -111.9261 },
    bedrooms: 7,
    bathrooms: 8,
    sqft: 15000,
    yearBuilt: 2020,
    images: ["/placeholder.svg?height=300&width=400&text=Arizona+Desert+Estate"],
    features: ["Pool", "Tennis Court", "Desert Views"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Arkansas
  {
    id: "prop_arkansas_1",
    address: "321 Ozark Mountain Road",
    city: "Bentonville",
    state: "AR",
    zipCode: "72712",
    value: 4200000,
    propertyType: "estate",
    ownerName: "Retail Dynasty Holdings",
    ownerType: "corporation",
    ownerWealth: 95000000,
    coordinates: { lat: 36.3729, lng: -94.2088 },
    bedrooms: 6,
    bathrooms: 5,
    sqft: 10000,
    yearBuilt: 2016,
    images: ["/placeholder.svg?height=300&width=400&text=Arkansas+Estate"],
    features: ["Mountain Views", "Wine Cellar", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // California
  {
    id: "prop_california_1",
    address: "456 Beverly Hills Drive",
    city: "Beverly Hills",
    state: "CA",
    zipCode: "90210",
    value: 25000000,
    propertyType: "mansion",
    ownerName: "Entertainment Mogul Inc",
    ownerType: "corporation",
    ownerWealth: 450000000,
    coordinates: { lat: 34.0736, lng: -118.4004 },
    bedrooms: 12,
    bathrooms: 15,
    sqft: 25000,
    yearBuilt: 2021,
    images: ["/placeholder.svg?height=300&width=400&text=Beverly+Hills+Mansion"],
    features: ["Pool", "Wine Cellar", "Home Theater", "Tennis Court"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prop_california_2",
    address: "789 Pacific Coast Highway",
    city: "Malibu",
    state: "CA",
    zipCode: "90265",
    value: 18500000,
    propertyType: "estate",
    ownerName: "Celebrity Holdings Trust",
    ownerType: "trust",
    ownerWealth: 320000000,
    coordinates: { lat: 34.0259, lng: -118.7798 },
    bedrooms: 8,
    bathrooms: 10,
    sqft: 18000,
    yearBuilt: 2019,
    images: ["/placeholder.svg?height=300&width=400&text=Malibu+Oceanfront"],
    features: ["Ocean View", "Private Beach", "Guest House", "Infinity Pool"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Colorado
  {
    id: "prop_colorado_1",
    address: "654 Aspen Mountain Road",
    city: "Aspen",
    state: "CO",
    zipCode: "81611",
    value: 15200000,
    propertyType: "lodge",
    ownerName: "Alpine Holdings Group",
    ownerType: "corporation",
    ownerWealth: 280000000,
    coordinates: { lat: 39.1911, lng: -106.8175 },
    bedrooms: 8,
    bathrooms: 9,
    sqft: 16000,
    yearBuilt: 2017,
    images: ["/placeholder.svg?height=300&width=400&text=Aspen+Ski+Lodge"],
    features: ["Ski Access", "Hot Tub", "Fireplace", "Mountain Views"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Connecticut
  {
    id: "prop_connecticut_1",
    address: "987 Greenwich Gold Coast",
    city: "Greenwich",
    state: "CT",
    zipCode: "06830",
    value: 12500000,
    propertyType: "estate",
    ownerName: "Wall Street Titan",
    ownerType: "individual",
    ownerWealth: 650000000,
    coordinates: { lat: 41.0534, lng: -73.5387 },
    bedrooms: 8,
    bathrooms: 10,
    sqft: 14000,
    yearBuilt: 2015,
    images: ["/placeholder.svg?height=300&width=400&text=Greenwich+Estate"],
    features: ["Pool", "Tennis Court", "Wine Cellar", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Delaware
  {
    id: "prop_delaware_1",
    address: "234 Wilmington Corporate Plaza",
    city: "Wilmington",
    state: "DE",
    zipCode: "19801",
    value: 4200000,
    propertyType: "penthouse",
    ownerName: "Chemical Dynasty Trust",
    ownerType: "trust",
    ownerWealth: 180000000,
    coordinates: { lat: 39.7391, lng: -75.5398 },
    bedrooms: 6,
    bathrooms: 5,
    sqft: 9000,
    yearBuilt: 2020,
    images: ["/placeholder.svg?height=300&width=400&text=Delaware+Penthouse"],
    features: ["City Views", "Rooftop Deck", "Concierge"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Florida
  {
    id: "prop_florida_1",
    address: "567 Miami Beach Ocean Drive",
    city: "Miami Beach",
    state: "FL",
    zipCode: "33139",
    value: 9800000,
    propertyType: "penthouse",
    ownerName: "International Real Estate Mogul",
    ownerType: "corporation",
    ownerWealth: 340000000,
    coordinates: { lat: 25.7907, lng: -80.13 },
    bedrooms: 5,
    bathrooms: 6,
    sqft: 8500,
    yearBuilt: 2020,
    images: ["/placeholder.svg?height=300&width=400&text=Miami+Beach+Penthouse"],
    features: ["Ocean View", "Private Beach", "Rooftop Pool", "Concierge"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Georgia
  {
    id: "prop_georgia_1",
    address: "890 Atlanta Buckhead Estate",
    city: "Atlanta",
    state: "GA",
    zipCode: "30309",
    value: 6800000,
    propertyType: "mansion",
    ownerName: "Southern Capital Group",
    ownerType: "corporation",
    ownerWealth: 195000000,
    coordinates: { lat: 33.8688, lng: -84.3717 },
    bedrooms: 7,
    bathrooms: 8,
    sqft: 13000,
    yearBuilt: 2018,
    images: ["/placeholder.svg?height=300&width=400&text=Atlanta+Mansion"],
    features: ["Pool", "Tennis Court", "Wine Cellar", "Gardens"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Hawaii
  {
    id: "prop_hawaii_1",
    address: "123 Maui Oceanfront Estate",
    city: "Wailea",
    state: "HI",
    zipCode: "96753",
    value: 22000000,
    propertyType: "estate",
    ownerName: "Pacific Paradise Holdings",
    ownerType: "corporation",
    ownerWealth: 580000000,
    coordinates: { lat: 20.6947, lng: -156.4444 },
    bedrooms: 8,
    bathrooms: 10,
    sqft: 18000,
    yearBuilt: 2020,
    images: ["/placeholder.svg?height=300&width=400&text=Hawaii+Oceanfront"],
    features: ["Ocean View", "Private Beach", "Infinity Pool", "Guest Villas"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Idaho
  {
    id: "prop_idaho_1",
    address: "456 Sun Valley Ski Estate",
    city: "Sun Valley",
    state: "ID",
    zipCode: "83353",
    value: 8500000,
    propertyType: "lodge",
    ownerName: "Mountain Holdings Corp",
    ownerType: "corporation",
    ownerWealth: 185000000,
    coordinates: { lat: 43.6963, lng: -114.3574 },
    bedrooms: 7,
    bathrooms: 8,
    sqft: 14000,
    yearBuilt: 2018,
    images: ["/placeholder.svg?height=300&width=400&text=Idaho+Ski+Lodge"],
    features: ["Ski Access", "Mountain Views", "Hot Tub", "Fireplace"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Illinois
  {
    id: "prop_illinois_1",
    address: "789 Chicago Gold Coast Penthouse",
    city: "Chicago",
    state: "IL",
    zipCode: "60611",
    value: 8900000,
    propertyType: "penthouse",
    ownerName: "Windy City Holdings",
    ownerType: "corporation",
    ownerWealth: 285000000,
    coordinates: { lat: 41.8986, lng: -87.6233 },
    bedrooms: 4,
    bathrooms: 5,
    sqft: 7000,
    yearBuilt: 2019,
    images: ["/placeholder.svg?height=300&width=400&text=Chicago+Penthouse"],
    features: ["Lake Views", "Rooftop Deck", "Concierge", "Wine Storage"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Indiana
  {
    id: "prop_indiana_1",
    address: "321 Indianapolis Racing Estate",
    city: "Indianapolis",
    state: "IN",
    zipCode: "46240",
    value: 3200000,
    propertyType: "estate",
    ownerName: "Motorsports Holdings LLC",
    ownerType: "llc",
    ownerWealth: 85000000,
    coordinates: { lat: 39.7684, lng: -86.1581 },
    bedrooms: 6,
    bathrooms: 5,
    sqft: 8500,
    yearBuilt: 2015,
    images: ["/placeholder.svg?height=300&width=400&text=Indianapolis+Estate"],
    features: ["Racing Track", "Garage", "Pool", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Iowa
  {
    id: "prop_iowa_1",
    address: "654 Des Moines Insurance Estate",
    city: "West Des Moines",
    state: "IA",
    zipCode: "50266",
    value: 2400000,
    propertyType: "mansion",
    ownerName: "Insurance Dynasty Holdings",
    ownerType: "corporation",
    ownerWealth: 95000000,
    coordinates: { lat: 41.5868, lng: -93.7112 },
    bedrooms: 5,
    bathrooms: 4,
    sqft: 7000,
    yearBuilt: 2017,
    images: ["/placeholder.svg?height=300&width=400&text=Iowa+Mansion"],
    features: ["Pool", "Wine Cellar", "Home Office", "Gardens"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Kansas
  {
    id: "prop_kansas_1",
    address: "987 Kansas City Agricultural Estate",
    city: "Kansas City",
    state: "KS",
    zipCode: "66101",
    value: 2800000,
    propertyType: "ranch",
    ownerName: "Agricultural Investment Group",
    ownerType: "corporation",
    ownerWealth: 125000000,
    coordinates: { lat: 39.1142, lng: -94.6275 },
    bedrooms: 6,
    bathrooms: 5,
    sqft: 8000,
    yearBuilt: 2016,
    images: ["/placeholder.svg?height=300&width=400&text=Kansas+Ranch"],
    features: ["Stables", "Barn", "Pool", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Kentucky
  {
    id: "prop_kentucky_1",
    address: "234 Louisville Bourbon Estate",
    city: "Louisville",
    state: "KY",
    zipCode: "40202",
    value: 3800000,
    propertyType: "mansion",
    ownerName: "Bourbon Dynasty Holdings",
    ownerType: "corporation",
    ownerWealth: 165000000,
    coordinates: { lat: 38.2527, lng: -85.7585 },
    bedrooms: 6,
    bathrooms: 6,
    sqft: 9500,
    yearBuilt: 2017,
    images: ["/placeholder.svg?height=300&width=400&text=Kentucky+Mansion"],
    features: ["Bourbon Cellar", "Stables", "Pool", "Gardens"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Louisiana
  {
    id: "prop_louisiana_1",
    address: "567 New Orleans Garden District",
    city: "New Orleans",
    state: "LA",
    zipCode: "70115",
    value: 4500000,
    propertyType: "mansion",
    ownerName: "Creole Heritage Trust",
    ownerType: "trust",
    ownerWealth: 145000000,
    coordinates: { lat: 29.9511, lng: -90.0715 },
    bedrooms: 6,
    bathrooms: 5,
    sqft: 9000,
    yearBuilt: 1890,
    images: ["/placeholder.svg?height=300&width=400&text=New+Orleans+Mansion"],
    features: ["Historic", "Courtyard", "Balconies", "Wine Cellar"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Maine
  {
    id: "prop_maine_1",
    address: "890 Bar Harbor Coastal Estate",
    city: "Bar Harbor",
    state: "ME",
    zipCode: "04609",
    value: 6800000,
    propertyType: "estate",
    ownerName: "New England Maritime Holdings",
    ownerType: "corporation",
    ownerWealth: 185000000,
    coordinates: { lat: 44.3876, lng: -68.2039 },
    bedrooms: 7,
    bathrooms: 6,
    sqft: 11000,
    yearBuilt: 2016,
    images: ["/placeholder.svg?height=300&width=400&text=Maine+Coastal+Estate"],
    features: ["Ocean Views", "Private Beach", "Lighthouse", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Maryland
  {
    id: "prop_maryland_1",
    address: "123 Potomac Political Estate",
    city: "Potomac",
    state: "MD",
    zipCode: "20854",
    value: 8500000,
    propertyType: "mansion",
    ownerName: "Beltway Holdings Group",
    ownerType: "corporation",
    ownerWealth: 285000000,
    coordinates: { lat: 39.0458, lng: -77.2086 },
    bedrooms: 8,
    bathrooms: 9,
    sqft: 14000,
    yearBuilt: 2019,
    images: ["/placeholder.svg?height=300&width=400&text=Maryland+Mansion"],
    features: ["Pool", "Tennis Court", "Wine Cellar", "Home Theater"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Massachusetts
  {
    id: "prop_massachusetts_1",
    address: "456 Boston Beacon Hill Mansion",
    city: "Boston",
    state: "MA",
    zipCode: "02108",
    value: 12500000,
    propertyType: "mansion",
    ownerName: "New England Dynasty Holdings",
    ownerType: "corporation",
    ownerWealth: 485000000,
    coordinates: { lat: 42.3601, lng: -71.0589 },
    bedrooms: 8,
    bathrooms: 7,
    sqft: 12000,
    yearBuilt: 1885,
    images: ["/placeholder.svg?height=300&width=400&text=Boston+Historic+Mansion"],
    features: ["Historic", "Garden", "Wine Cellar", "Library"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Michigan
  {
    id: "prop_michigan_1",
    address: "789 Detroit Automotive Estate",
    city: "Detroit",
    state: "MI",
    zipCode: "48201",
    value: 3800000,
    propertyType: "mansion",
    ownerName: "Automotive Dynasty Holdings",
    ownerType: "corporation",
    ownerWealth: 285000000,
    coordinates: { lat: 42.3314, lng: -83.0458 },
    bedrooms: 6,
    bathrooms: 5,
    sqft: 9000,
    yearBuilt: 2018,
    images: ["/placeholder.svg?height=300&width=400&text=Michigan+Mansion"],
    features: ["Car Collection Garage", "Pool", "Wine Cellar", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Minnesota
  {
    id: "prop_minnesota_1",
    address: "321 Minneapolis Lake Estate",
    city: "Minneapolis",
    state: "MN",
    zipCode: "55401",
    value: 4200000,
    propertyType: "estate",
    ownerName: "Twin Cities Holdings Group",
    ownerType: "corporation",
    ownerWealth: 165000000,
    coordinates: { lat: 44.9778, lng: -93.265 },
    bedrooms: 6,
    bathrooms: 6,
    sqft: 9500,
    yearBuilt: 2017,
    images: ["/placeholder.svg?height=300&width=400&text=Minnesota+Lake+Estate"],
    features: ["Lake Views", "Dock", "Pool", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Mississippi
  {
    id: "prop_mississippi_1",
    address: "654 Jackson Cotton Estate",
    city: "Jackson",
    state: "MS",
    zipCode: "39201",
    value: 2800000,
    propertyType: "mansion",
    ownerName: "Southern Agriculture Holdings",
    ownerType: "corporation",
    ownerWealth: 95000000,
    coordinates: { lat: 32.2988, lng: -90.1848 },
    bedrooms: 6,
    bathrooms: 5,
    sqft: 8500,
    yearBuilt: 1900,
    images: ["/placeholder.svg?height=300&width=400&text=Mississippi+Mansion"],
    features: ["Historic", "Columns", "Gardens", "Pool"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Missouri
  {
    id: "prop_missouri_1",
    address: "987 St. Louis Brewing Estate",
    city: "St. Louis",
    state: "MO",
    zipCode: "63101",
    value: 3800000,
    propertyType: "mansion",
    ownerName: "Brewing Dynasty Holdings",
    ownerType: "corporation",
    ownerWealth: 285000000,
    coordinates: { lat: 38.627, lng: -90.1994 },
    bedrooms: 6,
    bathrooms: 5,
    sqft: 9000,
    yearBuilt: 2018,
    images: ["/placeholder.svg?height=300&width=400&text=Missouri+Mansion"],
    features: ["Brewery", "Pool", "Wine Cellar", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Montana
  {
    id: "prop_montana_1",
    address: "234 Big Sky Ranch Estate",
    city: "Big Sky",
    state: "MT",
    zipCode: "59716",
    value: 12500000,
    propertyType: "ranch",
    ownerName: "Mountain Ranch Holdings",
    ownerType: "corporation",
    ownerWealth: 485000000,
    coordinates: { lat: 45.2849, lng: -111.4083 },
    bedrooms: 8,
    bathrooms: 7,
    sqft: 15000,
    yearBuilt: 2020,
    images: ["/placeholder.svg?height=300&width=400&text=Montana+Ranch"],
    features: ["Mountain Views", "Stables", "Guest Lodge", "Ski Access"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Nebraska
  {
    id: "prop_nebraska_1",
    address: "567 Omaha Investment Estate",
    city: "Omaha",
    state: "NE",
    zipCode: "68101",
    value: 3200000,
    propertyType: "mansion",
    ownerName: "Investment Holdings Group",
    ownerType: "corporation",
    ownerWealth: 285000000,
    coordinates: { lat: 41.2565, lng: -95.9345 },
    bedrooms: 6,
    bathrooms: 5,
    sqft: 8500,
    yearBuilt: 2018,
    images: ["/placeholder.svg?height=300&width=400&text=Nebraska+Mansion"],
    features: ["Pool", "Wine Cellar", "Home Office", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Nevada
  {
    id: "prop_nevada_1",
    address: "890 Las Vegas Casino Estate",
    city: "Las Vegas",
    state: "NV",
    zipCode: "89101",
    value: 15800000,
    propertyType: "mansion",
    ownerName: "Gaming Empire Holdings",
    ownerType: "corporation",
    ownerWealth: 650000000,
    coordinates: { lat: 36.1699, lng: -115.1398 },
    bedrooms: 6,
    bathrooms: 8,
    sqft: 12000,
    yearBuilt: 2021,
    images: ["/placeholder.svg?height=300&width=400&text=Las+Vegas+Mansion"],
    features: ["Strip Views", "Pool", "Casino Room", "Wine Cellar"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // New Hampshire
  {
    id: "prop_newhampshire_1",
    address: "123 White Mountains Estate",
    city: "North Conway",
    state: "NH",
    zipCode: "03860",
    value: 4200000,
    propertyType: "lodge",
    ownerName: "Mountain Holdings Trust",
    ownerType: "trust",
    ownerWealth: 125000000,
    coordinates: { lat: 44.0542, lng: -71.1253 },
    bedrooms: 6,
    bathrooms: 5,
    sqft: 9000,
    yearBuilt: 2018,
    images: ["/placeholder.svg?height=300&width=400&text=New+Hampshire+Lodge"],
    features: ["Mountain Views", "Ski Access", "Fireplace", "Hot Tub"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // New Jersey
  {
    id: "prop_newjersey_1",
    address: "456 Princeton University Estate",
    city: "Princeton",
    state: "NJ",
    zipCode: "08540",
    value: 6800000,
    propertyType: "mansion",
    ownerName: "Academic Holdings Group",
    ownerType: "corporation",
    ownerWealth: 285000000,
    coordinates: { lat: 40.3573, lng: -74.6672 },
    bedrooms: 7,
    bathrooms: 6,
    sqft: 11000,
    yearBuilt: 2019,
    images: ["/placeholder.svg?height=300&width=400&text=New+Jersey+Mansion"],
    features: ["Library", "Pool", "Tennis Court", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // New Mexico
  {
    id: "prop_newmexico_1",
    address: "789 Santa Fe Adobe Estate",
    city: "Santa Fe",
    state: "NM",
    zipCode: "87501",
    value: 3800000,
    propertyType: "estate",
    ownerName: "Southwest Art Holdings",
    ownerType: "corporation",
    ownerWealth: 125000000,
    coordinates: { lat: 35.687, lng: -105.9378 },
    bedrooms: 5,
    bathrooms: 4,
    sqft: 8000,
    yearBuilt: 2018,
    images: ["/placeholder.svg?height=300&width=400&text=New+Mexico+Adobe"],
    features: ["Adobe Architecture", "Courtyard", "Art Gallery", "Pool"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // New York
  {
    id: "prop_newyork_1",
    address: "123 Park Avenue",
    city: "New York",
    state: "NY",
    zipCode: "10016",
    value: 28500000,
    propertyType: "penthouse",
    ownerName: "Wall Street Titan",
    ownerType: "individual",
    ownerWealth: 1200000000,
    coordinates: { lat: 40.7505, lng: -73.9934 },
    bedrooms: 6,
    bathrooms: 8,
    sqft: 10000,
    yearBuilt: 2020,
    images: ["/placeholder.svg?height=300&width=400&text=Manhattan+Penthouse"],
    features: ["Central Park Views", "Rooftop Deck", "Wine Cellar", "Concierge"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prop_newyork_2",
    address: "321 Meadow Lane",
    city: "East Hampton",
    state: "NY",
    zipCode: "11937",
    value: 22000000,
    propertyType: "estate",
    ownerName: "Real Estate Dynasty",
    ownerType: "corporation",
    ownerWealth: 850000000,
    coordinates: { lat: 40.9629, lng: -72.1989 },
    bedrooms: 10,
    bathrooms: 12,
    sqft: 22000,
    yearBuilt: 2019,
    images: ["/placeholder.svg?height=300&width=400&text=Hamptons+Estate"],
    features: ["Ocean Views", "Private Beach", "Tennis Court", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // North Carolina
  {
    id: "prop_northcarolina_1",
    address: "654 Charlotte Banking Estate",
    city: "Charlotte",
    state: "NC",
    zipCode: "28202",
    value: 4800000,
    propertyType: "mansion",
    ownerName: "Banking Dynasty Holdings",
    ownerType: "corporation",
    ownerWealth: 285000000,
    coordinates: { lat: 35.2271, lng: -80.8431 },
    bedrooms: 6,
    bathrooms: 6,
    sqft: 10000,
    yearBuilt: 2019,
    images: ["/placeholder.svg?height=300&width=400&text=North+Carolina+Mansion"],
    features: ["Pool", "Wine Cellar", "Home Office", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // North Dakota
  {
    id: "prop_northdakota_1",
    address: "987 Fargo Agricultural Estate",
    city: "Fargo",
    state: "ND",
    zipCode: "58102",
    value: 1800000,
    propertyType: "ranch",
    ownerName: "Agricultural Holdings Group",
    ownerType: "corporation",
    ownerWealth: 85000000,
    coordinates: { lat: 46.8772, lng: -96.7898 },
    bedrooms: 4,
    bathrooms: 3,
    sqft: 6000,
    yearBuilt: 2017,
    images: ["/placeholder.svg?height=300&width=400&text=North+Dakota+Ranch"],
    features: ["Farmland", "Barn", "Stables", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Ohio
  {
    id: "prop_ohio_1",
    address: "234 Cleveland Industrial Estate",
    city: "Cleveland",
    state: "OH",
    zipCode: "44101",
    value: 3800000,
    propertyType: "mansion",
    ownerName: "Industrial Holdings Group",
    ownerType: "corporation",
    ownerWealth: 185000000,
    coordinates: { lat: 41.4993, lng: -81.6944 },
    bedrooms: 6,
    bathrooms: 5,
    sqft: 9000,
    yearBuilt: 2018,
    images: ["/placeholder.svg?height=300&width=400&text=Ohio+Mansion"],
    features: ["Lake Views", "Pool", "Wine Cellar", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Oklahoma
  {
    id: "prop_oklahoma_1",
    address: "567 Oklahoma City Oil Estate",
    city: "Oklahoma City",
    state: "OK",
    zipCode: "73102",
    value: 3200000,
    propertyType: "mansion",
    ownerName: "Oil Dynasty Holdings",
    ownerType: "corporation",
    ownerWealth: 285000000,
    coordinates: { lat: 35.4676, lng: -97.5164 },
    bedrooms: 6,
    bathrooms: 5,
    sqft: 8500,
    yearBuilt: 2018,
    images: ["/placeholder.svg?height=300&width=400&text=Oklahoma+Mansion"],
    features: ["Pool", "Oil Derrick Views", "Wine Cellar", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Oregon
  {
    id: "prop_oregon_1",
    address: "890 Portland Tech Estate",
    city: "Portland",
    state: "OR",
    zipCode: "97201",
    value: 4800000,
    propertyType: "mansion",
    ownerName: "Pacific Northwest Ventures",
    ownerType: "corporation",
    ownerWealth: 185000000,
    coordinates: { lat: 45.5152, lng: -122.6784 },
    bedrooms: 6,
    bathrooms: 6,
    sqft: 10000,
    yearBuilt: 2019,
    images: ["/placeholder.svg?height=300&width=400&text=Oregon+Mansion"],
    features: ["Mountain Views", "Pool", "Wine Cellar", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Pennsylvania
  {
    id: "prop_pennsylvania_1",
    address: "123 Philadelphia Historic Estate",
    city: "Philadelphia",
    state: "PA",
    zipCode: "19102",
    value: 6800000,
    propertyType: "mansion",
    ownerName: "Colonial Holdings Trust",
    ownerType: "trust",
    ownerWealth: 285000000,
    coordinates: { lat: 39.9526, lng: -75.1652 },
    bedrooms: 7,
    bathrooms: 6,
    sqft: 11000,
    yearBuilt: 1890,
    images: ["/placeholder.svg?height=300&width=400&text=Pennsylvania+Historic"],
    features: ["Historic", "Library", "Wine Cellar", "Gardens"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Rhode Island
  {
    id: "prop_rhodeisland_1",
    address: "456 Newport Gilded Age Mansion",
    city: "Newport",
    state: "RI",
    zipCode: "02840",
    value: 18500000,
    propertyType: "mansion",
    ownerName: "New England Dynasty",
    ownerType: "trust",
    ownerWealth: 650000000,
    coordinates: { lat: 41.4901, lng: -71.3128 },
    bedrooms: 12,
    bathrooms: 10,
    sqft: 20000,
    yearBuilt: 1895,
    images: ["/placeholder.svg?height=300&width=400&text=Rhode+Island+Mansion"],
    features: ["Ocean Views", "Historic", "Ballroom", "Gardens"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // South Carolina
  {
    id: "prop_southcarolina_1",
    address: "789 Charleston Historic Estate",
    city: "Charleston",
    state: "SC",
    zipCode: "29401",
    value: 5800000,
    propertyType: "mansion",
    ownerName: "Southern Heritage Holdings",
    ownerType: "trust",
    ownerWealth: 185000000,
    coordinates: { lat: 32.7767, lng: -79.9311 },
    bedrooms: 6,
    bathrooms: 5,
    sqft: 9500,
    yearBuilt: 1850,
    images: ["/placeholder.svg?height=300&width=400&text=South+Carolina+Historic"],
    features: ["Historic", "Piazzas", "Gardens", "Carriage House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // South Dakota
  {
    id: "prop_southdakota_1",
    address: "321 Rapid City Mining Estate",
    city: "Rapid City",
    state: "SD",
    zipCode: "57701",
    value: 2200000,
    propertyType: "ranch",
    ownerName: "Mining Holdings Corporation",
    ownerType: "corporation",
    ownerWealth: 125000000,
    coordinates: { lat: 44.0805, lng: -103.231 },
    bedrooms: 5,
    bathrooms: 4,
    sqft: 7000,
    yearBuilt: 2018,
    images: ["/placeholder.svg?height=300&width=400&text=South+Dakota+Ranch"],
    features: ["Mountain Views", "Mining Operations", "Stables", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Tennessee
  {
    id: "prop_tennessee_1",
    address: "654 Nashville Music Estate",
    city: "Nashville",
    state: "TN",
    zipCode: "37201",
    value: 6800000,
    propertyType: "mansion",
    ownerName: "Music Industry Holdings",
    ownerType: "corporation",
    ownerWealth: 285000000,
    coordinates: { lat: 36.1627, lng: -86.7816 },
    bedrooms: 7,
    bathrooms: 6,
    sqft: 11000,
    yearBuilt: 2019,
    images: ["/placeholder.svg?height=300&width=400&text=Tennessee+Music+Mansion"],
    features: ["Recording Studio", "Pool", "Wine Cellar", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Texas
  {
    id: "prop_texas_1",
    address: "987 Dallas Oil Empire Estate",
    city: "Dallas",
    state: "TX",
    zipCode: "75201",
    value: 12500000,
    propertyType: "mansion",
    ownerName: "Texas Oil Dynasty",
    ownerType: "corporation",
    ownerWealth: 850000000,
    coordinates: { lat: 32.7767, lng: -96.797 },
    bedrooms: 8,
    bathrooms: 10,
    sqft: 16000,
    yearBuilt: 2020,
    images: ["/placeholder.svg?height=300&width=400&text=Texas+Oil+Mansion"],
    features: ["Pool", "Tennis Court", "Wine Cellar", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prop_texas_2",
    address: "234 Houston Energy Estate",
    city: "Houston",
    state: "TX",
    zipCode: "77002",
    value: 8900000,
    propertyType: "mansion",
    ownerName: "Energy Holdings Corporation",
    ownerType: "corporation",
    ownerWealth: 485000000,
    coordinates: { lat: 29.7604, lng: -95.3698 },
    bedrooms: 7,
    bathrooms: 8,
    sqft: 14000,
    yearBuilt: 2019,
    images: ["/placeholder.svg?height=300&width=400&text=Houston+Energy+Mansion"],
    features: ["Pool", "Wine Cellar", "Home Theater", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Utah
  {
    id: "prop_utah_1",
    address: "567 Park City Ski Estate",
    city: "Park City",
    state: "UT",
    zipCode: "84060",
    value: 8500000,
    propertyType: "lodge",
    ownerName: "Mountain Resort Holdings",
    ownerType: "corporation",
    ownerWealth: 285000000,
    coordinates: { lat: 40.6461, lng: -111.498 },
    bedrooms: 7,
    bathrooms: 7,
    sqft: 12000,
    yearBuilt: 2019,
    images: ["/placeholder.svg?height=300&width=400&text=Utah+Ski+Lodge"],
    features: ["Ski Access", "Mountain Views", "Hot Tub", "Wine Cellar"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Vermont
  {
    id: "prop_vermont_1",
    address: "890 Stowe Ski Resort Estate",
    city: "Stowe",
    state: "VT",
    zipCode: "05672",
    value: 4800000,
    propertyType: "lodge",
    ownerName: "Vermont Holdings Trust",
    ownerType: "trust",
    ownerWealth: 125000000,
    coordinates: { lat: 44.4654, lng: -72.6874 },
    bedrooms: 6,
    bathrooms: 5,
    sqft: 9500,
    yearBuilt: 2018,
    images: ["/placeholder.svg?height=300&width=400&text=Vermont+Ski+Lodge"],
    features: ["Ski Access", "Mountain Views", "Fireplace", "Hot Tub"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Virginia
  {
    id: "prop_virginia_1",
    address: "123 Virginia Beach Resort Estate",
    city: "Virginia Beach",
    state: "VA",
    zipCode: "23451",
    value: 4800000,
    propertyType: "estate",
    ownerName: "Coastal Holdings Corporation",
    ownerType: "corporation",
    ownerWealth: 165000000,
    coordinates: { lat: 36.8529, lng: -75.978 },
    bedrooms: 6,
    bathrooms: 5,
    sqft: 9000,
    yearBuilt: 2019,
    images: ["/placeholder.svg?height=300&width=400&text=Virginia+Beach+Estate"],
    features: ["Ocean Views", "Private Beach", "Pool", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Washington
  {
    id: "prop_washington_1",
    address: "456 Seattle Tech Estate",
    city: "Seattle",
    state: "WA",
    zipCode: "98101",
    value: 12500000,
    propertyType: "mansion",
    ownerName: "Pacific Northwest Tech Giant",
    ownerType: "corporation",
    ownerWealth: 2800000000,
    coordinates: { lat: 47.6062, lng: -122.3321 },
    bedrooms: 8,
    bathrooms: 9,
    sqft: 15000,
    yearBuilt: 2020,
    images: ["/placeholder.svg?height=300&width=400&text=Seattle+Tech+Mansion"],
    features: ["Sound Views", "Pool", "Wine Cellar", "Home Theater"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // West Virginia
  {
    id: "prop_westvirginia_1",
    address: "789 Charleston Coal Estate",
    city: "Charleston",
    state: "WV",
    zipCode: "25301",
    value: 2200000,
    propertyType: "mansion",
    ownerName: "Coal Dynasty Holdings",
    ownerType: "corporation",
    ownerWealth: 165000000,
    coordinates: { lat: 38.3498, lng: -81.6326 },
    bedrooms: 5,
    bathrooms: 4,
    sqft: 7000,
    yearBuilt: 2017,
    images: ["/placeholder.svg?height=300&width=400&text=West+Virginia+Mansion"],
    features: ["Mountain Views", "Pool", "Wine Cellar", "Guest House"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Wisconsin
  {
    id: "prop_wisconsin_1",
    address: "321 Milwaukee Brewing Estate",
    city: "Milwaukee",
    state: "WI",
    zipCode: "53202",
    value: 3800000,
    propertyType: "mansion",
    ownerName: "Brewing Dynasty Holdings",
    ownerType: "corporation",
    ownerWealth: 185000000,
    coordinates: { lat: 43.0389, lng: -87.9065 },
    bedrooms: 6,
    bathrooms: 5,
    sqft: 9000,
    yearBuilt: 2018,
    images: ["/placeholder.svg?height=300&width=400&text=Wisconsin+Brewing+Mansion"],
    features: ["Brewery", "Lake Views", "Pool", "Wine Cellar"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Wyoming
  {
    id: "prop_wyoming_1",
    address: "654 Jackson Hole Ski Estate",
    city: "Jackson Hole",
    state: "WY",
    zipCode: "83025",
    value: 18500000,
    propertyType: "lodge",
    ownerName: "Mountain Holdings Corporation",
    ownerType: "corporation",
    ownerWealth: 650000000,
    coordinates: { lat: 43.4799, lng: -110.7624 },
    bedrooms: 9,
    bathrooms: 10,
    sqft: 18000,
    yearBuilt: 2020,
    images: ["/placeholder.svg?height=300&width=400&text=Wyoming+Ski+Lodge"],
    features: ["Ski Access", "Mountain Views", "Hot Tub", "Guest Lodge"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Washington DC
  {
    id: "prop_dc_1",
    address: "987 Georgetown Political Estate",
    city: "Washington",
    state: "DC",
    zipCode: "20007",
    value: 15800000,
    propertyType: "mansion",
    ownerName: "Political Dynasty Holdings",
    ownerType: "corporation",
    ownerWealth: 485000000,
    coordinates: { lat: 38.9072, lng: -77.0369 },
    bedrooms: 8,
    bathrooms: 9,
    sqft: 14000,
    yearBuilt: 2019,
    images: ["/placeholder.svg?height=300&width=400&text=DC+Political+Mansion"],
    features: ["Historic District", "Pool", "Wine Cellar", "Security"],
    isActive: true,
    dataSource: "sample",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)

    // Extract filter parameters
    const filters: PropertyFilter = {
      minValue:
        searchParams.get("minValue") && searchParams.get("minValue") !== "0"
          ? Number.parseInt(searchParams.get("minValue")!)
          : undefined,
      maxValue:
        searchParams.get("maxValue") && searchParams.get("maxValue") !== "10000000"
          ? Number.parseInt(searchParams.get("maxValue")!)
          : undefined,
      propertyType:
        searchParams.get("propertyType") === "all" || !searchParams.get("propertyType")
          ? undefined
          : searchParams.get("propertyType"),
      ownerType:
        searchParams.get("ownerType") === "all" || !searchParams.get("ownerType")
          ? undefined
          : searchParams.get("ownerType"),
      wealthRange:
        searchParams.get("wealthRange") === "all" || !searchParams.get("wealthRange")
          ? undefined
          : searchParams.get("wealthRange"),
      location: searchParams.get("search") || searchParams.get("location") || undefined,
    }

    const limit = Math.min(Number.parseInt(searchParams.get("limit") || "50"), 100)
    const skip = Math.max(Number.parseInt(searchParams.get("skip") || "0"), 0)

    console.log("🔍 Properties API - Using sample data with filters:", JSON.stringify(filters, null, 2))

    // Filter sample properties
    const properties = sampleProperties.filter((property) => {
      // Value range filter
      if (filters.minValue && property.value < filters.minValue) return false
      if (filters.maxValue && property.value > filters.maxValue) return false

      // Property type filter
      if (filters.propertyType) {
        const typeMatch = property.propertyType.toLowerCase().includes(filters.propertyType.toLowerCase())
        if (!typeMatch) return false
      }

      // Owner type filter
      if (filters.ownerType) {
        const ownerMatch = property.ownerType.toLowerCase().includes(filters.ownerType.toLowerCase())
        if (!ownerMatch) return false
      }

      // Location filter
      if (filters.location) {
        const locationLower = filters.location.toLowerCase()
        const addressMatch = property.address.toLowerCase().includes(locationLower)
        const cityMatch = property.city.toLowerCase().includes(locationLower)
        const stateMatch = property.state.toLowerCase().includes(locationLower)
        if (!addressMatch && !cityMatch && !stateMatch) return false
      }

      // Wealth range filter
      if (filters.wealthRange && filters.wealthRange !== "all") {
        const wealthRanges: Record<string, [number, number]> = {
          "1m-5m": [1000000, 5000000],
          "5m-10m": [5000000, 10000000],
          "10m-25m": [10000000, 25000000],
          "25m-50m": [25000000, 50000000],
          "50m+": [50000000, 999999999],
        }

        const range = wealthRanges[filters.wealthRange]
        if (range) {
          if (property.ownerWealth < range[0] || property.ownerWealth > range[1]) return false
        }
      }

      return true
    })

    // Sort by value (highest first)
    properties.sort((a, b) => b.value - a.value)

    // Apply pagination
    const paginatedProperties = properties.slice(skip, skip + limit)

    // Calculate market stats
    const marketStats = {
      totalProperties: properties.length,
      averageValue: properties.reduce((sum, p) => sum + p.value, 0) / properties.length,
      minValue: Math.min(...properties.map((p) => p.value)),
      maxValue: Math.max(...properties.map((p) => p.value)),
      averageWealthOwner: properties.reduce((sum, p) => sum + p.ownerWealth, 0) / properties.length,
    }

    console.log("📊 Sample data results:", {
      total: properties.length,
      returned: paginatedProperties.length,
      marketStats,
    })

    return NextResponse.json({
      properties: paginatedProperties,
      total: properties.length,
      marketStats,
      filters,
      dataSource: "sample",
      success: true,
    })
  } catch (error) {
    console.error("❌ Properties API error:", error)

    return NextResponse.json({
      properties: [],
      total: 0,
      marketStats: {},
      filters: {},
      dataSource: "error",
      error: "Service temporarily unavailable",
      success: false,
    })
  }
}

export async function POST(request: NextRequest) {
  try {
    const propertyData = await request.json()

    // Generate unique ID
    propertyData.id = `prop_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`

    console.log("✅ Property created (sample mode):", propertyData.id)

    return NextResponse.json(propertyData, { status: 201 })
  } catch (error) {
    console.error("❌ Create property error:", error)
    return NextResponse.json(
      {
        error: "Failed to create property",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    )
  }
}
