import { NextResponse, type NextRequest } from "next/server"

// Comprehensive property data for all 50 states + DC
const sampleProperties = [
  // Alabama
  {
    id: "search_al_1",
    type: "property",
    title: "Historic Birmingham Estate",
    subtitle: "Birmingham, AL • Historic Mansion • $2.8M",
    address: "123 Historic Mansion Drive",
    city: "Birmingham",
    state: "AL",
    zipCode: "35203",
    value: 2800000,
    ownerName: "Southern Heritage Trust",
    ownerWealth: 45000000,
    propertyType: "mansion",
    coordinates: { lat: 33.5186, lng: -86.8104 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    images: ["/placeholder.svg?height=300&width=400&text=Birmingham+Historic+Estate"],
    features: ["Historic Architecture", "Garden", "Wine Cellar", "Guest House"],
  },
  {
    id: "search_al_2",
    type: "property",
    title: "Montgomery Capitol Estate",
    subtitle: "Montgomery, AL • Executive Estate • $1.9M",
    address: "456 Capitol Hill Estate",
    city: "Montgomery",
    state: "AL",
    zipCode: "36104",
    value: 1900000,
    ownerName: "Alabama Holdings LLC",
    ownerWealth: 35000000,
    propertyType: "estate",
    coordinates: { lat: 32.3617, lng: -86.2792 },
    bedrooms: 5,
    bathrooms: 6,
    sqft: 7200,
    images: ["/placeholder.svg?height=300&width=400&text=Montgomery+Capitol+Estate"],
    features: ["Pool", "Tennis Court", "Home Office", "Security System"],
  },

  // Alaska
  {
    id: "search_ak_1",
    type: "property",
    title: "Anchorage Wilderness Lodge",
    subtitle: "Anchorage, AK • Luxury Lodge • $4.5M",
    address: "456 Wilderness Lodge Road",
    city: "Anchorage",
    state: "AK",
    zipCode: "99501",
    value: 4500000,
    ownerName: "Arctic Holdings Corp",
    ownerWealth: 85000000,
    propertyType: "lodge",
    coordinates: { lat: 61.2181, lng: -149.9003 },
    bedrooms: 8,
    bathrooms: 9,
    sqft: 12000,
    images: ["/placeholder.svg?height=300&width=400&text=Alaska+Wilderness+Lodge"],
    features: ["Mountain Views", "Fireplace", "Hot Tub", "Helicopter Pad"],
  },
  {
    id: "search_ak_2",
    type: "property",
    title: "Fairbanks Northern Estate",
    subtitle: "Fairbanks, AK • Northern Estate • $3.2M",
    address: "789 Northern Lights Estate",
    city: "Fairbanks",
    state: "AK",
    zipCode: "99701",
    value: 3200000,
    ownerName: "Midnight Sun Holdings",
    ownerWealth: 65000000,
    propertyType: "estate",
    coordinates: { lat: 64.8378, lng: -147.7164 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 9500,
    images: ["/placeholder.svg?height=300&width=400&text=Fairbanks+Northern+Estate"],
    features: ["Aurora Views", "Heated Garage", "Generator", "Storage"],
  },

  // Arizona
  {
    id: "search_az_1",
    type: "property",
    title: "Scottsdale Desert Estate",
    subtitle: "Scottsdale, AZ • Desert Luxury • $7.2M",
    address: "789 Desert Mountain Estate",
    city: "Scottsdale",
    state: "AZ",
    zipCode: "85262",
    value: 7200000,
    ownerName: "Desert Luxury Holdings",
    ownerWealth: 125000000,
    propertyType: "estate",
    coordinates: { lat: 33.4942, lng: -111.9261 },
    bedrooms: 7,
    bathrooms: 9,
    sqft: 11500,
    images: ["/placeholder.svg?height=300&width=400&text=Scottsdale+Desert+Estate"],
    features: ["Desert Views", "Infinity Pool", "Golf Course", "Spa"],
  },
  {
    id: "search_az_2",
    type: "property",
    title: "Phoenix Desert Ridge",
    subtitle: "Phoenix, AZ • Modern Mansion • $4.8M",
    address: "456 Phoenix Desert Ridge",
    city: "Phoenix",
    state: "AZ",
    zipCode: "85028",
    value: 4800000,
    ownerName: "Southwest Holdings",
    ownerWealth: 95000000,
    propertyType: "mansion",
    coordinates: { lat: 33.4484, lng: -112.074 },
    bedrooms: 6,
    bathrooms: 8,
    sqft: 9800,
    images: ["/placeholder.svg?height=300&width=400&text=Phoenix+Desert+Ridge"],
    features: ["Pool", "Home Theater", "Wine Cellar", "Guest Suite"],
  },

  // Arkansas
  {
    id: "search_ar_1",
    type: "property",
    title: "Bentonville Executive Estate",
    subtitle: "Bentonville, AR • Corporate Estate • $4.2M",
    address: "321 Ozark Mountain Road",
    city: "Bentonville",
    state: "AR",
    zipCode: "72712",
    value: 4200000,
    ownerName: "Retail Dynasty Holdings",
    ownerWealth: 95000000,
    propertyType: "estate",
    coordinates: { lat: 36.3729, lng: -94.2088 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8900,
    images: ["/placeholder.svg?height=300&width=400&text=Bentonville+Executive+Estate"],
    features: ["Home Office", "Conference Room", "Pool", "Tennis Court"],
  },

  // California
  {
    id: "search_ca_1",
    type: "property",
    title: "Beverly Hills Mansion",
    subtitle: "Beverly Hills, CA • Celebrity Estate • $25M",
    address: "456 Beverly Hills Drive",
    city: "Beverly Hills",
    state: "CA",
    zipCode: "90210",
    value: 25000000,
    ownerName: "Entertainment Mogul Inc",
    ownerWealth: 450000000,
    propertyType: "mansion",
    coordinates: { lat: 34.0736, lng: -118.4004 },
    bedrooms: 12,
    bathrooms: 15,
    sqft: 25000,
    images: ["/placeholder.svg?height=300&width=400&text=Beverly+Hills+Mansion"],
    features: ["Pool", "Wine Cellar", "Home Theater", "Tennis Court"],
  },
  {
    id: "search_ca_2",
    type: "property",
    title: "Malibu Oceanfront Estate",
    subtitle: "Malibu, CA • Beachfront Luxury • $18.5M",
    address: "789 Pacific Coast Highway",
    city: "Malibu",
    state: "CA",
    zipCode: "90265",
    value: 18500000,
    ownerName: "Celebrity Holdings Trust",
    ownerWealth: 320000000,
    propertyType: "estate",
    coordinates: { lat: 34.0259, lng: -118.7798 },
    bedrooms: 8,
    bathrooms: 10,
    sqft: 15000,
    images: ["/placeholder.svg?height=300&width=400&text=Malibu+Oceanfront+Estate"],
    features: ["Ocean View", "Private Beach", "Pool", "Guest House"],
  },
  {
    id: "search_ca_3",
    type: "property",
    title: "Palo Alto Tech Estate",
    subtitle: "Palo Alto, CA • Tech Billionaire • $22M",
    address: "1234 University Ave",
    city: "Palo Alto",
    state: "CA",
    zipCode: "94301",
    value: 22000000,
    ownerName: "Tech Billionaire Holdings",
    ownerWealth: 15000000000,
    propertyType: "estate",
    coordinates: { lat: 37.4419, lng: -122.143 },
    bedrooms: 10,
    bathrooms: 12,
    sqft: 18000,
    images: ["/placeholder.svg?height=300&width=400&text=Palo+Alto+Tech+Estate"],
    features: ["Smart Home", "Solar Panels", "Electric Car Charging", "Home Office"],
  },
  {
    id: "search_ca_4",
    type: "property",
    title: "Napa Valley Vineyard Estate",
    subtitle: "Napa, CA • Wine Estate • $18.5M",
    address: "567 Napa Valley Vineyard",
    city: "Napa",
    state: "CA",
    zipCode: "94558",
    value: 18500000,
    ownerName: "Wine Dynasty Holdings",
    ownerWealth: 380000000,
    propertyType: "vineyard",
    coordinates: { lat: 38.2975, lng: -122.286 },
    bedrooms: 8,
    bathrooms: 10,
    sqft: 14000,
    images: ["/placeholder.svg?height=300&width=400&text=Napa+Valley+Vineyard"],
    features: ["Vineyard", "Wine Cellar", "Tasting Room", "Guest Cottage"],
  },
  {
    id: "search_ca_5",
    type: "property",
    title: "San Francisco Pacific Heights",
    subtitle: "San Francisco, CA • Urban Mansion • $16.8M",
    address: "890 Pacific Heights",
    city: "San Francisco",
    state: "CA",
    zipCode: "94109",
    value: 16800000,
    ownerName: "Tech Venture Capital",
    ownerWealth: 850000000,
    propertyType: "mansion",
    coordinates: { lat: 37.7749, lng: -122.4194 },
    bedrooms: 7,
    bathrooms: 9,
    sqft: 12500,
    images: ["/placeholder.svg?height=300&width=400&text=San+Francisco+Pacific+Heights"],
    features: ["City Views", "Rooftop Deck", "Wine Cellar", "Elevator"],
  },

  // Colorado
  {
    id: "search_co_1",
    type: "property",
    title: "Aspen Mountain Lodge",
    subtitle: "Aspen, CO • Ski Resort Estate • $15.2M",
    address: "654 Aspen Mountain Road",
    city: "Aspen",
    state: "CO",
    zipCode: "81611",
    value: 15200000,
    ownerName: "Alpine Holdings Group",
    ownerWealth: 280000000,
    propertyType: "lodge",
    coordinates: { lat: 39.1911, lng: -106.8175 },
    bedrooms: 8,
    bathrooms: 9,
    sqft: 16000,
    images: ["/placeholder.svg?height=300&width=400&text=Aspen+Mountain+Lodge"],
    features: ["Ski Access", "Hot Tub", "Fireplace", "Mountain Views"],
  },
  {
    id: "search_co_2",
    type: "property",
    title: "Vail Ski Resort Estate",
    subtitle: "Vail, CO • Alpine Luxury • $12.8M",
    address: "321 Vail Ski Resort",
    city: "Vail",
    state: "CO",
    zipCode: "81657",
    value: 12800000,
    ownerName: "Mountain Resort Holdings",
    ownerWealth: 485000000,
    propertyType: "lodge",
    coordinates: { lat: 39.6403, lng: -106.3742 },
    bedrooms: 7,
    bathrooms: 8,
    sqft: 14500,
    images: ["/placeholder.svg?height=300&width=400&text=Vail+Ski+Resort+Estate"],
    features: ["Ski-in/Ski-out", "Heated Floors", "Wine Cellar", "Spa"],
  },

  // Connecticut
  {
    id: "search_ct_1",
    type: "property",
    title: "Greenwich Gold Coast Estate",
    subtitle: "Greenwich, CT • Financial Elite • $12.5M",
    address: "987 Greenwich Gold Coast",
    city: "Greenwich",
    state: "CT",
    zipCode: "06830",
    value: 12500000,
    ownerName: "Wall Street Titan",
    ownerWealth: 650000000,
    propertyType: "estate",
    coordinates: { lat: 41.0534, lng: -73.5387 },
    bedrooms: 8,
    bathrooms: 10,
    sqft: 15000,
    images: ["/placeholder.svg?height=300&width=400&text=Greenwich+Gold+Coast"],
    features: ["Waterfront", "Pool", "Tennis Court", "Guest House"],
  },

  // Delaware
  {
    id: "search_de_1",
    type: "property",
    title: "Wilmington Corporate Plaza",
    subtitle: "Wilmington, DE • Executive Penthouse • $4.2M",
    address: "234 Wilmington Corporate Plaza",
    city: "Wilmington",
    state: "DE",
    zipCode: "19801",
    value: 4200000,
    ownerName: "Chemical Dynasty Trust",
    ownerWealth: 180000000,
    propertyType: "penthouse",
    coordinates: { lat: 39.7391, lng: -75.5398 },
    bedrooms: 4,
    bathrooms: 5,
    sqft: 6500,
    images: ["/placeholder.svg?height=300&width=400&text=Wilmington+Corporate+Plaza"],
    features: ["City Views", "Concierge", "Rooftop Access", "Private Elevator"],
  },

  // Florida
  {
    id: "search_fl_1",
    type: "property",
    title: "Miami Beach Ocean Drive",
    subtitle: "Miami Beach, FL • Oceanfront Penthouse • $9.8M",
    address: "567 Miami Beach Ocean Drive",
    city: "Miami Beach",
    state: "FL",
    zipCode: "33139",
    value: 9800000,
    ownerName: "International Real Estate Mogul",
    ownerWealth: 340000000,
    propertyType: "penthouse",
    coordinates: { lat: 25.7907, lng: -80.13 },
    bedrooms: 5,
    bathrooms: 6,
    sqft: 8500,
    images: ["/placeholder.svg?height=300&width=400&text=Miami+Beach+Penthouse"],
    features: ["Ocean View", "Private Beach", "Rooftop Pool", "Concierge"],
  },
  {
    id: "search_fl_2",
    type: "property",
    title: "Naples Luxury Estate",
    subtitle: "Naples, FL • Golf Course Estate • $7.8M",
    address: "234 Naples Luxury Estate",
    city: "Naples",
    state: "FL",
    zipCode: "34102",
    value: 7800000,
    ownerName: "Retirement Luxury Holdings",
    ownerWealth: 285000000,
    propertyType: "estate",
    coordinates: { lat: 26.142, lng: -81.7948 },
    bedrooms: 6,
    bathrooms: 8,
    sqft: 10500,
    images: ["/placeholder.svg?height=300&width=400&text=Naples+Luxury+Estate"],
    features: ["Golf Course", "Pool", "Tennis Court", "Guest House"],
  },
  {
    id: "search_fl_3",
    type: "property",
    title: "Key West Oceanfront Villa",
    subtitle: "Key West, FL • Tropical Paradise • $6.2M",
    address: "890 Key West Oceanfront",
    city: "Key West",
    state: "FL",
    zipCode: "33040",
    value: 6200000,
    ownerName: "Caribbean Holdings LLC",
    ownerWealth: 185000000,
    propertyType: "villa",
    coordinates: { lat: 24.5551, lng: -81.78 },
    bedrooms: 5,
    bathrooms: 6,
    sqft: 7500,
    images: ["/placeholder.svg?height=300&width=400&text=Key+West+Oceanfront"],
    features: ["Ocean View", "Private Dock", "Pool", "Tropical Gardens"],
  },

  // Georgia
  {
    id: "search_ga_1",
    type: "property",
    title: "Atlanta Buckhead Estate",
    subtitle: "Atlanta, GA • Southern Luxury • $6.8M",
    address: "890 Atlanta Buckhead Estate",
    city: "Atlanta",
    state: "GA",
    zipCode: "30309",
    value: 6800000,
    ownerName: "Southern Capital Group",
    ownerWealth: 195000000,
    propertyType: "mansion",
    coordinates: { lat: 33.8688, lng: -84.3717 },
    bedrooms: 7,
    bathrooms: 9,
    sqft: 11000,
    images: ["/placeholder.svg?height=300&width=400&text=Atlanta+Buckhead+Estate"],
    features: ["Pool", "Tennis Court", "Wine Cellar", "Guest House"],
  },
  {
    id: "search_ga_2",
    type: "property",
    title: "Savannah Historic Estate",
    subtitle: "Savannah, GA • Historic Mansion • $4.2M",
    address: "567 Savannah Historic Estate",
    city: "Savannah",
    state: "GA",
    zipCode: "31401",
    value: 4200000,
    ownerName: "Southern Heritage Holdings",
    ownerWealth: 165000000,
    propertyType: "mansion",
    coordinates: { lat: 32.0835, lng: -81.0998 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    images: ["/placeholder.svg?height=300&width=400&text=Savannah+Historic+Estate"],
    features: ["Historic Architecture", "Garden", "Carriage House", "Fountain"],
  },

  // Hawaii
  {
    id: "search_hi_1",
    type: "property",
    title: "Maui Oceanfront Estate",
    subtitle: "Wailea, HI • Paradise Estate • $22M",
    address: "123 Maui Oceanfront Estate",
    city: "Wailea",
    state: "HI",
    zipCode: "96753",
    value: 22000000,
    ownerName: "Pacific Paradise Holdings",
    ownerWealth: 580000000,
    propertyType: "estate",
    coordinates: { lat: 20.6947, lng: -156.4444 },
    bedrooms: 8,
    bathrooms: 10,
    sqft: 18000,
    images: ["/placeholder.svg?height=300&width=400&text=Maui+Oceanfront+Estate"],
    features: ["Ocean View", "Private Beach", "Infinity Pool", "Guest Villas"],
  },
  {
    id: "search_hi_2",
    type: "property",
    title: "Honolulu Diamond Head Estate",
    subtitle: "Honolulu, HI • Luxury Estate • $18.5M",
    address: "456 Diamond Head Estate",
    city: "Honolulu",
    state: "HI",
    zipCode: "96815",
    value: 18500000,
    ownerName: "Island Holdings Trust",
    ownerWealth: 425000000,
    propertyType: "estate",
    coordinates: { lat: 21.3099, lng: -157.8581 },
    bedrooms: 7,
    bathrooms: 9,
    sqft: 14500,
    images: ["/placeholder.svg?height=300&width=400&text=Honolulu+Diamond+Head"],
    features: ["Mountain Views", "Pool", "Tennis Court", "Tropical Gardens"],
  },

  // Idaho
  {
    id: "search_id_1",
    type: "property",
    title: "Sun Valley Ski Estate",
    subtitle: "Sun Valley, ID • Mountain Resort • $8.5M",
    address: "456 Sun Valley Ski Estate",
    city: "Sun Valley",
    state: "ID",
    zipCode: "83353",
    value: 8500000,
    ownerName: "Mountain Holdings Corp",
    ownerWealth: 185000000,
    propertyType: "lodge",
    coordinates: { lat: 43.6963, lng: -114.3574 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 9500,
    images: ["/placeholder.svg?height=300&width=400&text=Sun+Valley+Ski+Estate"],
    features: ["Ski Access", "Mountain Views", "Hot Tub", "Fireplace"],
  },

  // Illinois
  {
    id: "search_il_1",
    type: "property",
    title: "Chicago Gold Coast Penthouse",
    subtitle: "Chicago, IL • Urban Luxury • $8.9M",
    address: "789 Chicago Gold Coast",
    city: "Chicago",
    state: "IL",
    zipCode: "60611",
    value: 8900000,
    ownerName: "Windy City Holdings",
    ownerWealth: 285000000,
    propertyType: "penthouse",
    coordinates: { lat: 41.8986, lng: -87.6233 },
    bedrooms: 5,
    bathrooms: 6,
    sqft: 7500,
    images: ["/placeholder.svg?height=300&width=400&text=Chicago+Gold+Coast"],
    features: ["Lake Views", "Rooftop Deck", "Concierge", "Wine Storage"],
  },
  {
    id: "search_il_2",
    type: "property",
    title: "Lake Forest Estate",
    subtitle: "Lake Forest, IL • Suburban Luxury • $6.8M",
    address: "456 Lake Forest Estate",
    city: "Lake Forest",
    state: "IL",
    zipCode: "60045",
    value: 6800000,
    ownerName: "Chicago Finance Dynasty",
    ownerWealth: 385000000,
    propertyType: "estate",
    coordinates: { lat: 42.2587, lng: -87.8406 },
    bedrooms: 7,
    bathrooms: 8,
    sqft: 12000,
    images: ["/placeholder.svg?height=300&width=400&text=Lake+Forest+Estate"],
    features: ["Lake Access", "Pool", "Tennis Court", "Guest House"],
  },

  // Indiana
  {
    id: "search_in_1",
    type: "property",
    title: "Indianapolis Racing Estate",
    subtitle: "Indianapolis, IN • Motorsports Luxury • $3.2M",
    address: "321 Indianapolis Racing Estate",
    city: "Indianapolis",
    state: "IN",
    zipCode: "46240",
    value: 3200000,
    ownerName: "Motorsports Holdings LLC",
    ownerWealth: 85000000,
    propertyType: "estate",
    coordinates: { lat: 39.7684, lng: -86.1581 },
    bedrooms: 5,
    bathrooms: 6,
    sqft: 7800,
    images: ["/placeholder.svg?height=300&width=400&text=Indianapolis+Racing+Estate"],
    features: ["Car Collection Garage", "Pool", "Home Theater", "Workshop"],
  },

  // Iowa
  {
    id: "search_ia_1",
    type: "property",
    title: "Des Moines Insurance Estate",
    subtitle: "West Des Moines, IA • Executive Estate • $2.4M",
    address: "654 Des Moines Insurance Estate",
    city: "West Des Moines",
    state: "IA",
    zipCode: "50266",
    value: 2400000,
    ownerName: "Insurance Dynasty Holdings",
    ownerWealth: 95000000,
    propertyType: "mansion",
    coordinates: { lat: 41.5868, lng: -93.7112 },
    bedrooms: 5,
    bathrooms: 6,
    sqft: 6800,
    images: ["/placeholder.svg?height=300&width=400&text=Des+Moines+Insurance+Estate"],
    features: ["Home Office", "Pool", "Wine Cellar", "Guest Suite"],
  },

  // Kansas
  {
    id: "search_ks_1",
    type: "property",
    title: "Kansas City Agricultural Estate",
    subtitle: "Kansas City, KS • Agricultural Investment • $2.8M",
    address: "987 Kansas City Agricultural",
    city: "Kansas City",
    state: "KS",
    zipCode: "66101",
    value: 2800000,
    ownerName: "Agricultural Investment Group",
    ownerWealth: 125000000,
    propertyType: "ranch",
    coordinates: { lat: 39.1142, lng: -94.6275 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    images: ["/placeholder.svg?height=300&width=400&text=Kansas+City+Agricultural"],
    features: ["Ranch Land", "Barn", "Equipment Storage", "Guest House"],
  },

  // Kentucky
  {
    id: "search_ky_1",
    type: "property",
    title: "Louisville Bourbon Estate",
    subtitle: "Louisville, KY • Bourbon Dynasty • $3.8M",
    address: "234 Louisville Bourbon Estate",
    city: "Louisville",
    state: "KY",
    zipCode: "40207",
    value: 3800000,
    ownerName: "Bourbon Dynasty Holdings",
    ownerWealth: 165000000,
    propertyType: "mansion",
    coordinates: { lat: 38.2527, lng: -85.7585 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8200,
    images: ["/placeholder.svg?height=300&width=400&text=Louisville+Bourbon+Estate"],
    features: ["Bourbon Cellar", "Pool", "Stables", "Guest House"],
  },

  // Louisiana
  {
    id: "search_la_1",
    type: "property",
    title: "New Orleans Garden District",
    subtitle: "New Orleans, LA • Historic Mansion • $4.5M",
    address: "567 New Orleans Garden District",
    city: "New Orleans",
    state: "LA",
    zipCode: "70115",
    value: 4500000,
    ownerName: "Creole Heritage Trust",
    ownerWealth: 145000000,
    propertyType: "mansion",
    coordinates: { lat: 29.9511, lng: -90.0715 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8800,
    images: ["/placeholder.svg?height=300&width=400&text=New+Orleans+Garden+District"],
    features: ["Historic Architecture", "Courtyard", "Balconies", "Garden"],
  },

  // Maine
  {
    id: "search_me_1",
    type: "property",
    title: "Bar Harbor Coastal Estate",
    subtitle: "Bar Harbor, ME • Coastal Luxury • $6.8M",
    address: "890 Bar Harbor Coastal Estate",
    city: "Bar Harbor",
    state: "ME",
    zipCode: "04609",
    value: 6800000,
    ownerName: "New England Maritime Holdings",
    ownerWealth: 185000000,
    propertyType: "estate",
    coordinates: { lat: 44.3876, lng: -68.2039 },
    bedrooms: 7,
    bathrooms: 8,
    sqft: 9500,
    images: ["/placeholder.svg?height=300&width=400&text=Bar+Harbor+Coastal+Estate"],
    features: ["Ocean Views", "Private Dock", "Lighthouse", "Guest Cottage"],
  },

  // Maryland
  {
    id: "search_md_1",
    type: "property",
    title: "Potomac Political Estate",
    subtitle: "Potomac, MD • Political Elite • $8.5M",
    address: "123 Potomac Political Estate",
    city: "Potomac",
    state: "MD",
    zipCode: "20854",
    value: 8500000,
    ownerName: "Beltway Holdings Group",
    ownerWealth: 285000000,
    propertyType: "mansion",
    coordinates: { lat: 39.0458, lng: -77.2086 },
    bedrooms: 7,
    bathrooms: 9,
    sqft: 11500,
    images: ["/placeholder.svg?height=300&width=400&text=Potomac+Political+Estate"],
    features: ["Security System", "Home Office", "Pool", "Tennis Court"],
  },

  // Massachusetts
  {
    id: "search_ma_1",
    type: "property",
    title: "Boston Beacon Hill Mansion",
    subtitle: "Boston, MA • Historic Elite • $12.5M",
    address: "456 Boston Beacon Hill",
    city: "Boston",
    state: "MA",
    zipCode: "02108",
    value: 12500000,
    ownerName: "New England Dynasty Holdings",
    ownerWealth: 485000000,
    propertyType: "mansion",
    coordinates: { lat: 42.3601, lng: -71.0589 },
    bedrooms: 8,
    bathrooms: 10,
    sqft: 14000,
    images: ["/placeholder.svg?height=300&width=400&text=Boston+Beacon+Hill"],
    features: ["Historic Architecture", "Garden", "Wine Cellar", "Library"],
  },
  {
    id: "search_ma_2",
    type: "property",
    title: "Martha's Vineyard Estate",
    subtitle: "Martha's Vineyard, MA • Island Paradise • $14.5M",
    address: "789 Martha's Vineyard Estate",
    city: "Martha's Vineyard",
    state: "MA",
    zipCode: "02539",
    value: 14500000,
    ownerName: "New England Maritime Trust",
    ownerWealth: 585000000,
    propertyType: "estate",
    coordinates: { lat: 41.3811, lng: -70.6178 },
    bedrooms: 8,
    bathrooms: 10,
    sqft: 15500,
    images: ["/placeholder.svg?height=300&width=400&text=Martha's+Vineyard+Estate"],
    features: ["Ocean Views", "Private Beach", "Pool", "Guest House"],
  },

  // Michigan
  {
    id: "search_mi_1",
    type: "property",
    title: "Detroit Automotive Estate",
    subtitle: "Detroit, MI • Automotive Legacy • $3.8M",
    address: "789 Detroit Automotive Estate",
    city: "Detroit",
    state: "MI",
    zipCode: "48226",
    value: 3800000,
    ownerName: "Automotive Dynasty Holdings",
    ownerWealth: 285000000,
    propertyType: "mansion",
    coordinates: { lat: 42.3314, lng: -83.0458 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    images: ["/placeholder.svg?height=300&width=400&text=Detroit+Automotive+Estate"],
    features: ["Car Collection Garage", "Workshop", "Pool", "Home Theater"],
  },

  // Minnesota
  {
    id: "search_mn_1",
    type: "property",
    title: "Minneapolis Lake Estate",
    subtitle: "Minneapolis, MN • Lake Luxury • $4.2M",
    address: "321 Minneapolis Lake Estate",
    city: "Minneapolis",
    state: "MN",
    zipCode: "55416",
    value: 4200000,
    ownerName: "Twin Cities Holdings Group",
    ownerWealth: 165000000,
    propertyType: "estate",
    coordinates: { lat: 44.9778, lng: -93.265 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8800,
    images: ["/placeholder.svg?height=300&width=400&text=Minneapolis+Lake+Estate"],
    features: ["Lake Access", "Dock", "Pool", "Guest House"],
  },

  // Mississippi
  {
    id: "search_ms_1",
    type: "property",
    title: "Jackson Cotton Estate",
    subtitle: "Jackson, MS • Agricultural Heritage • $2.8M",
    address: "654 Jackson Cotton Estate",
    city: "Jackson",
    state: "MS",
    zipCode: "39202",
    value: 2800000,
    ownerName: "Southern Agriculture Holdings",
    ownerWealth: 95000000,
    propertyType: "mansion",
    coordinates: { lat: 32.2988, lng: -90.1848 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8200,
    images: ["/placeholder.svg?height=300&width=400&text=Jackson+Cotton+Estate"],
    features: ["Historic Plantation", "Gardens", "Guest House", "Stables"],
  },

  // Missouri
  {
    id: "search_mo_1",
    type: "property",
    title: "St. Louis Brewing Estate",
    subtitle: "St. Louis, MO • Brewing Dynasty • $3.8M",
    address: "987 St. Louis Brewing Estate",
    city: "St. Louis",
    state: "MO",
    zipCode: "63108",
    value: 3800000,
    ownerName: "Brewing Dynasty Holdings",
    ownerWealth: 285000000,
    propertyType: "mansion",
    coordinates: { lat: 38.627, lng: -90.1994 },
    bedrooms: 6,
    bathrooms: 8,
    sqft: 9200,
    images: ["/placeholder.svg?height=300&width=400&text=St+Louis+Brewing+Estate"],
    features: ["Brewery", "Tasting Room", "Pool", "Entertainment Area"],
  },

  // Montana
  {
    id: "search_mt_1",
    type: "property",
    title: "Big Sky Ranch Estate",
    subtitle: "Big Sky, MT • Mountain Ranch • $12.5M",
    address: "234 Big Sky Ranch Estate",
    city: "Big Sky",
    state: "MT",
    zipCode: "59716",
    value: 12500000,
    ownerName: "Mountain Ranch Holdings",
    ownerWealth: 485000000,
    propertyType: "ranch",
    coordinates: { lat: 45.2849, lng: -111.4083 },
    bedrooms: 8,
    bathrooms: 9,
    sqft: 15000,
    images: ["/placeholder.svg?height=300&width=400&text=Big+Sky+Ranch+Estate"],
    features: ["Mountain Views", "Ranch Land", "Stables", "Guest Lodge"],
  },

  // Nebraska
  {
    id: "search_ne_1",
    type: "property",
    title: "Omaha Investment Estate",
    subtitle: "Omaha, NE • Investment Elite • $3.2M",
    address: "567 Omaha Investment Estate",
    city: "Omaha",
    state: "NE",
    zipCode: "68114",
    value: 3200000,
    ownerName: "Investment Holdings Group",
    ownerWealth: 285000000,
    propertyType: "mansion",
    coordinates: { lat: 41.2565, lng: -95.9345 },
    bedrooms: 5,
    bathrooms: 6,
    sqft: 7500,
    images: ["/placeholder.svg?height=300&width=400&text=Omaha+Investment+Estate"],
    features: ["Home Office", "Pool", "Wine Cellar", "Guest Suite"],
  },

  // Nevada
  {
    id: "search_nv_1",
    type: "property",
    title: "Las Vegas Casino Estate",
    subtitle: "Las Vegas, NV • Gaming Empire • $15.8M",
    address: "890 Las Vegas Casino Estate",
    city: "Las Vegas",
    state: "NV",
    zipCode: "89109",
    value: 15800000,
    ownerName: "Gaming Empire Holdings",
    ownerWealth: 650000000,
    propertyType: "mansion",
    coordinates: { lat: 36.1699, lng: -115.1398 },
    bedrooms: 8,
    bathrooms: 10,
    sqft: 16000,
    images: ["/placeholder.svg?height=300&width=400&text=Las+Vegas+Casino+Estate"],
    features: ["Strip Views", "Pool", "Casino Room", "Wine Cellar"],
  },
  {
    id: "search_nv_2",
    type: "property",
    title: "Lake Tahoe Luxury Estate",
    subtitle: "Lake Tahoe, NV • Alpine Lake • $18.5M",
    address: "234 Lake Tahoe Luxury Estate",
    city: "Lake Tahoe",
    state: "NV",
    zipCode: "89449",
    value: 18500000,
    ownerName: "Alpine Lake Holdings",
    ownerWealth: 750000000,
    propertyType: "estate",
    coordinates: { lat: 39.0968, lng: -120.0324 },
    bedrooms: 9,
    bathrooms: 11,
    sqft: 17500,
    images: ["/placeholder.svg?height=300&width=400&text=Lake+Tahoe+Luxury+Estate"],
    features: ["Lake Views", "Private Beach", "Ski Access", "Guest House"],
  },

  // New Hampshire
  {
    id: "search_nh_1",
    type: "property",
    title: "White Mountains Estate",
    subtitle: "North Conway, NH • Mountain Retreat • $4.2M",
    address: "123 White Mountains Estate",
    city: "North Conway",
    state: "NH",
    zipCode: "03860",
    value: 4200000,
    ownerName: "Mountain Holdings Trust",
    ownerWealth: 125000000,
    propertyType: "lodge",
    coordinates: { lat: 44.0542, lng: -71.1253 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    images: ["/placeholder.svg?height=300&width=400&text=White+Mountains+Estate"],
    features: ["Mountain Views", "Ski Access", "Fireplace", "Hot Tub"],
  },

  // New Jersey
  {
    id: "search_nj_1",
    type: "property",
    title: "Princeton University Estate",
    subtitle: "Princeton, NJ • Academic Elite • $6.8M",
    address: "456 Princeton University Estate",
    city: "Princeton",
    state: "NJ",
    zipCode: "08540",
    value: 6800000,
    ownerName: "Academic Holdings Group",
    ownerWealth: 285000000,
    propertyType: "mansion",
    coordinates: { lat: 40.3573, lng: -74.6672 },
    bedrooms: 7,
    bathrooms: 8,
    sqft: 10500,
    images: ["/placeholder.svg?height=300&width=400&text=Princeton+University+Estate"],
    features: ["Library", "Home Office", "Pool", "Tennis Court"],
  },

  // New Mexico
  {
    id: "search_nm_1",
    type: "property",
    title: "Santa Fe Adobe Estate",
    subtitle: "Santa Fe, NM • Southwest Art • $3.8M",
    address: "789 Santa Fe Adobe Estate",
    city: "Santa Fe",
    state: "NM",
    zipCode: "87501",
    value: 3800000,
    ownerName: "Southwest Art Holdings",
    ownerWealth: 125000000,
    propertyType: "estate",
    coordinates: { lat: 35.687, lng: -105.9378 },
    bedrooms: 5,
    bathrooms: 6,
    sqft: 7800,
    images: ["/placeholder.svg?height=300&width=400&text=Santa+Fe+Adobe+Estate"],
    features: ["Adobe Architecture", "Art Gallery", "Courtyard", "Mountain Views"],
  },

  // New York
  {
    id: "search_ny_1",
    type: "property",
    title: "Manhattan Park Avenue Penthouse",
    subtitle: "New York, NY • Luxury Penthouse • $28.5M",
    address: "123 Park Avenue",
    city: "New York",
    state: "NY",
    zipCode: "10016",
    value: 28500000,
    ownerName: "Wall Street Titan",
    ownerWealth: 1200000000,
    propertyType: "penthouse",
    coordinates: { lat: 40.7505, lng: -73.9934 },
    bedrooms: 6,
    bathrooms: 8,
    sqft: 10000,
    images: ["/placeholder.svg?height=300&width=400&text=Manhattan+Penthouse"],
    features: ["Central Park Views", "Rooftop Deck", "Wine Cellar", "Concierge"],
  },
  {
    id: "search_ny_2",
    type: "property",
    title: "East Hampton Estate",
    subtitle: "East Hampton, NY • Hamptons Luxury • $22M",
    address: "321 Meadow Lane",
    city: "East Hampton",
    state: "NY",
    zipCode: "11937",
    value: 22000000,
    ownerName: "Real Estate Dynasty",
    ownerWealth: 850000000,
    propertyType: "estate",
    coordinates: { lat: 40.9629, lng: -72.1989 },
    bedrooms: 10,
    bathrooms: 12,
    sqft: 18000,
    images: ["/placeholder.svg?height=300&width=400&text=East+Hampton+Estate"],
    features: ["Ocean Views", "Private Beach", "Pool", "Tennis Court"],
  },
  {
    id: "search_ny_3",
    type: "property",
    title: "Fifth Avenue Penthouse",
    subtitle: "New York, NY • Ultra Luxury • $32M",
    address: "789 Fifth Avenue",
    city: "New York",
    state: "NY",
    zipCode: "10021",
    value: 32000000,
    ownerName: "Real Estate Mogul Empire",
    ownerWealth: 2500000000,
    propertyType: "penthouse",
    coordinates: { lat: 40.7614, lng: -73.9776 },
    bedrooms: 8,
    bathrooms: 10,
    sqft: 12000,
    images: ["/placeholder.svg?height=300&width=400&text=Fifth+Avenue+Penthouse"],
    features: ["Museum Views", "Private Elevator", "Wine Cellar", "Rooftop Terrace"],
  },
  {
    id: "search_ny_4",
    type: "property",
    title: "Brooklyn Heights Mansion",
    subtitle: "Brooklyn, NY • Historic Luxury • $8.5M",
    address: "456 Brooklyn Heights",
    city: "Brooklyn",
    state: "NY",
    zipCode: "11201",
    value: 8500000,
    ownerName: "Media Dynasty Holdings",
    ownerWealth: 485000000,
    propertyType: "mansion",
    coordinates: { lat: 40.6962, lng: -73.9442 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 9500,
    images: ["/placeholder.svg?height=300&width=400&text=Brooklyn+Heights+Mansion"],
    features: ["Harbor Views", "Historic Architecture", "Garden", "Wine Cellar"],
  },

  // North Carolina
  {
    id: "search_nc_1",
    type: "property",
    title: "Charlotte Banking Estate",
    subtitle: "Charlotte, NC • Financial District • $4.8M",
    address: "654 Charlotte Banking Estate",
    city: "Charlotte",
    state: "NC",
    zipCode: "28207",
    value: 4800000,
    ownerName: "Banking Dynasty Holdings",
    ownerWealth: 285000000,
    propertyType: "mansion",
    coordinates: { lat: 35.2271, lng: -80.8431 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8800,
    images: ["/placeholder.svg?height=300&width=400&text=Charlotte+Banking+Estate"],
    features: ["Home Office", "Pool", "Tennis Court", "Guest House"],
  },

  // North Dakota
  {
    id: "search_nd_1",
    type: "property",
    title: "Fargo Agricultural Estate",
    subtitle: "Fargo, ND • Agricultural Investment • $1.8M",
    address: "987 Fargo Agricultural Estate",
    city: "Fargo",
    state: "ND",
    zipCode: "58102",
    value: 1800000,
    ownerName: "Agricultural Holdings Group",
    ownerWealth: 85000000,
    propertyType: "ranch",
    coordinates: { lat: 46.8772, lng: -96.7898 },
    bedrooms: 4,
    bathrooms: 5,
    sqft: 6500,
    images: ["/placeholder.svg?height=300&width=400&text=Fargo+Agricultural+Estate"],
    features: ["Farm Land", "Barn", "Equipment Storage", "Guest House"],
  },

  // Ohio
  {
    id: "search_oh_1",
    type: "property",
    title: "Cleveland Industrial Estate",
    subtitle: "Cleveland, OH • Industrial Legacy • $3.8M",
    address: "234 Cleveland Industrial Estate",
    city: "Cleveland",
    state: "OH",
    zipCode: "44106",
    value: 3800000,
    ownerName: "Industrial Holdings Group",
    ownerWealth: 185000000,
    propertyType: "mansion",
    coordinates: { lat: 41.4993, lng: -81.6944 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    images: ["/placeholder.svg?height=300&width=400&text=Cleveland+Industrial+Estate"],
    features: ["Lake Views", "Pool", "Home Theater", "Wine Cellar"],
  },

  // Oklahoma
  {
    id: "search_ok_1",
    type: "property",
    title: "Oklahoma City Oil Estate",
    subtitle: "Oklahoma City, OK • Oil Dynasty • $3.2M",
    address: "567 Oklahoma City Oil Estate",
    city: "Oklahoma City",
    state: "OK",
    zipCode: "73102",
    value: 3200000,
    ownerName: "Oil Dynasty Holdings",
    ownerWealth: 285000000,
    propertyType: "mansion",
    coordinates: { lat: 35.4676, lng: -97.5164 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8200,
    images: ["/placeholder.svg?height=300&width=400&text=Oklahoma+City+Oil+Estate"],
    features: ["Pool", "Home Theater", "Wine Cellar", "Guest House"],
  },

  // Oregon
  {
    id: "search_or_1",
    type: "property",
    title: "Portland Tech Estate",
    subtitle: "Portland, OR • Tech Innovation • $4.8M",
    address: "890 Portland Tech Estate",
    city: "Portland",
    state: "OR",
    zipCode: "97205",
    value: 4800000,
    ownerName: "Pacific Northwest Ventures",
    ownerWealth: 185000000,
    propertyType: "mansion",
    coordinates: { lat: 45.5152, lng: -122.6784 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8800,
    images: ["/placeholder.svg?height=300&width=400&text=Portland+Tech+Estate"],
    features: ["Smart Home", "Solar Panels", "Pool", "Home Office"],
  },

  // Pennsylvania
  {
    id: "search_pa_1",
    type: "property",
    title: "Philadelphia Historic Estate",
    subtitle: "Philadelphia, PA • Colonial Heritage • $6.8M",
    address: "123 Philadelphia Historic Estate",
    city: "Philadelphia",
    state: "PA",
    zipCode: "19103",
    value: 6800000,
    ownerName: "Colonial Holdings Trust",
    ownerWealth: 285000000,
    propertyType: "mansion",
    coordinates: { lat: 39.9526, lng: -75.1652 },
    bedrooms: 7,
    bathrooms: 8,
    sqft: 10500,
    images: ["/placeholder.svg?height=300&width=400&text=Philadelphia+Historic+Estate"],
    features: ["Historic Architecture", "Garden", "Library", "Wine Cellar"],
  },

  // Rhode Island
  {
    id: "search_ri_1",
    type: "property",
    title: "Newport Gilded Age Mansion",
    subtitle: "Newport, RI • Gilded Age • $18.5M",
    address: "456 Newport Gilded Age",
    city: "Newport",
    state: "RI",
    zipCode: "02840",
    value: 18500000,
    ownerName: "New England Dynasty",
    ownerWealth: 650000000,
    propertyType: "mansion",
    coordinates: { lat: 41.4901, lng: -71.3128 },
    bedrooms: 12,
    bathrooms: 15,
    sqft: 22000,
    images: ["/placeholder.svg?height=300&width=400&text=Newport+Gilded+Age+Mansion"],
    features: ["Ocean Views", "Historic Architecture", "Ballroom", "Stables"],
  },

  // South Carolina
  {
    id: "search_sc_1",
    type: "property",
    title: "Charleston Historic Estate",
    subtitle: "Charleston, SC • Southern Charm • $5.8M",
    address: "789 Charleston Historic Estate",
    city: "Charleston",
    state: "SC",
    zipCode: "29401",
    value: 5800000,
    ownerName: "Southern Heritage Holdings",
    ownerWealth: 185000000,
    propertyType: "mansion",
    coordinates: { lat: 32.7767, lng: -79.9311 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 9200,
    images: ["/placeholder.svg?height=300&width=400&text=Charleston+Historic+Estate"],
    features: ["Historic Architecture", "Courtyard", "Garden", "Carriage House"],
  },

  // South Dakota
  {
    id: "search_sd_1",
    type: "property",
    title: "Rapid City Mining Estate",
    subtitle: "Rapid City, SD • Mining Heritage • $2.2M",
    address: "321 Rapid City Mining Estate",
    city: "Rapid City",
    state: "SD",
    zipCode: "57701",
    value: 2200000,
    ownerName: "Mining Holdings Corporation",
    ownerWealth: 125000000,
    propertyType: "ranch",
    coordinates: { lat: 44.0805, lng: -103.231 },
    bedrooms: 5,
    bathrooms: 6,
    sqft: 7200,
    images: ["/placeholder.svg?height=300&width=400&text=Rapid+City+Mining+Estate"],
    features: ["Mountain Views", "Ranch Land", "Barn", "Guest House"],
  },

  // Tennessee
  {
    id: "search_tn_1",
    type: "property",
    title: "Nashville Music Estate",
    subtitle: "Nashville, TN • Music Industry • $6.8M",
    address: "654 Nashville Music Estate",
    city: "Nashville",
    state: "TN",
    zipCode: "37215",
    value: 6800000,
    ownerName: "Music Industry Holdings",
    ownerWealth: 285000000,
    propertyType: "mansion",
    coordinates: { lat: 36.1627, lng: -86.7816 },
    bedrooms: 7,
    bathrooms: 8,
    sqft: 10200,
    images: ["/placeholder.svg?height=300&width=400&text=Nashville+Music+Estate"],
    features: ["Recording Studio", "Pool", "Entertainment Area", "Guest House"],
  },

  // Texas
  {
    id: "search_tx_1",
    type: "property",
    title: "Dallas Oil Empire Estate",
    subtitle: "Dallas, TX • Oil Executive • $12.5M",
    address: "987 Dallas Oil Empire Estate",
    city: "Dallas",
    state: "TX",
    zipCode: "75201",
    value: 12500000,
    ownerName: "Texas Oil Dynasty",
    ownerWealth: 850000000,
    propertyType: "mansion",
    coordinates: { lat: 32.7767, lng: -96.797 },
    bedrooms: 8,
    bathrooms: 10,
    sqft: 16000,
    images: ["/placeholder.svg?height=300&width=400&text=Dallas+Oil+Empire+Estate"],
    features: ["Pool", "Tennis Court", "Wine Cellar", "Guest House"],
  },
  {
    id: "search_tx_2",
    type: "property",
    title: "Houston Energy Estate",
    subtitle: "Houston, TX • Energy Sector • $8.9M",
    address: "234 Houston Energy Estate",
    city: "Houston",
    state: "TX",
    zipCode: "77019",
    value: 8900000,
    ownerName: "Energy Holdings Corporation",
    ownerWealth: 485000000,
    propertyType: "mansion",
    coordinates: { lat: 29.7604, lng: -95.3698 },
    bedrooms: 7,
    bathrooms: 9,
    sqft: 12500,
    images: ["/placeholder.svg?height=300&width=400&text=Houston+Energy+Estate"],
    features: ["Pool", "Home Theater", "Wine Cellar", "Guest Suite"],
  },
  {
    id: "search_tx_3",
    type: "property",
    title: "Austin Tech Campus",
    subtitle: "Austin, TX • Tech Innovation • $9.8M",
    address: "567 Austin Tech Campus",
    city: "Austin",
    state: "TX",
    zipCode: "78701",
    value: 9800000,
    ownerName: "Austin Tech Ventures",
    ownerWealth: 650000000,
    propertyType: "estate",
    coordinates: { lat: 30.2672, lng: -97.7431 },
    bedrooms: 8,
    bathrooms: 9,
    sqft: 14000,
    images: ["/placeholder.svg?height=300&width=400&text=Austin+Tech+Campus"],
    features: ["Smart Home", "Solar Panels", "Pool", "Home Office"],
  },

  // Utah
  {
    id: "search_ut_1",
    type: "property",
    title: "Park City Ski Estate",
    subtitle: "Park City, UT • Mountain Resort • $8.5M",
    address: "567 Park City Ski Estate",
    city: "Park City",
    state: "UT",
    zipCode: "84060",
    value: 8500000,
    ownerName: "Mountain Resort Holdings",
    ownerWealth: 285000000,
    propertyType: "lodge",
    coordinates: { lat: 40.6461, lng: -111.498 },
    bedrooms: 7,
    bathrooms: 8,
    sqft: 11500,
    images: ["/placeholder.svg?height=300&width=400&text=Park+City+Ski+Estate"],
    features: ["Ski Access", "Mountain Views", "Hot Tub", "Fireplace"],
  },

  // Vermont
  {
    id: "search_vt_1",
    type: "property",
    title: "Stowe Ski Resort Estate",
    subtitle: "Stowe, VT • Alpine Retreat • $4.8M",
    address: "890 Stowe Ski Resort Estate",
    city: "Stowe",
    state: "VT",
    zipCode: "05672",
    value: 4800000,
    ownerName: "Vermont Holdings Trust",
    ownerWealth: 125000000,
    propertyType: "lodge",
    coordinates: { lat: 44.4654, lng: -72.6874 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    images: ["/placeholder.svg?height=300&width=400&text=Stowe+Ski+Resort+Estate"],
    features: ["Ski Access", "Mountain Views", "Fireplace", "Hot Tub"],
  },

  // Virginia
  {
    id: "search_va_1",
    type: "property",
    title: "Virginia Beach Resort",
    subtitle: "Virginia Beach, VA • Coastal Luxury • $4.8M",
    address: "123 Virginia Beach Resort",
    city: "Virginia Beach",
    state: "VA",
    zipCode: "23451",
    value: 4800000,
    ownerName: "Coastal Holdings Corporation",
    ownerWealth: 165000000,
    propertyType: "estate",
    coordinates: { lat: 36.8529, lng: -75.978 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8800,
    images: ["/placeholder.svg?height=300&width=400&text=Virginia+Beach+Resort"],
    features: ["Ocean Views", "Private Beach", "Pool", "Guest House"],
  },

  // Washington
  {
    id: "search_wa_1",
    type: "property",
    title: "Seattle Tech Estate",
    subtitle: "Seattle, WA • Tech Billionaire • $12.5M",
    address: "456 Seattle Tech Estate",
    city: "Seattle",
    state: "WA",
    zipCode: "98101",
    value: 12500000,
    ownerName: "Pacific Northwest Tech Giant",
    ownerWealth: 2800000000,
    propertyType: "mansion",
    coordinates: { lat: 47.6062, lng: -122.3321 },
    bedrooms: 8,
    bathrooms: 9,
    sqft: 15000,
    images: ["/placeholder.svg?height=300&width=400&text=Seattle+Tech+Estate"],
    features: ["Sound Views", "Pool", "Wine Cellar", "Home Theater"],
  },
  {
    id: "search_wa_2",
    type: "property",
    title: "Bellevue Tech Estate",
    subtitle: "Bellevue, WA • Cloud Computing • $8.9M",
    address: "789 Bellevue Tech Estate",
    city: "Bellevue",
    state: "WA",
    zipCode: "98004",
    value: 8900000,
    ownerName: "Cloud Computing Dynasty",
    ownerWealth: 1850000000,
    propertyType: "mansion",
    coordinates: { lat: 47.6101, lng: -122.2015 },
    bedrooms: 7,
    bathrooms: 8,
    sqft: 12000,
    images: ["/placeholder.svg?height=300&width=400&text=Bellevue+Tech+Estate"],
    features: ["Lake Views", "Smart Home", "Pool", "Home Office"],
  },

  // West Virginia
  {
    id: "search_wv_1",
    type: "property",
    title: "Charleston Coal Estate",
    subtitle: "Charleston, WV • Coal Industry • $2.2M",
    address: "789 Charleston Coal Estate",
    city: "Charleston",
    state: "WV",
    zipCode: "25301",
    value: 2200000,
    ownerName: "Coal Dynasty Holdings",
    ownerWealth: 165000000,
    propertyType: "mansion",
    coordinates: { lat: 38.3498, lng: -81.6326 },
    bedrooms: 5,
    bathrooms: 6,
    sqft: 7200,
    images: ["/placeholder.svg?height=300&width=400&text=Charleston+Coal+Estate"],
    features: ["Mountain Views", "Pool", "Home Theater", "Guest Suite"],
  },

  // Wisconsin
  {
    id: "search_wi_1",
    type: "property",
    title: "Milwaukee Brewing Estate",
    subtitle: "Milwaukee, WI • Brewing Heritage • $3.8M",
    address: "321 Milwaukee Brewing Estate",
    city: "Milwaukee",
    state: "WI",
    zipCode: "53202",
    value: 3800000,
    ownerName: "Brewing Dynasty Holdings",
    ownerWealth: 185000000,
    propertyType: "mansion",
    coordinates: { lat: 43.0389, lng: -87.9065 },
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    images: ["/placeholder.svg?height=300&width=400&text=Milwaukee+Brewing+Estate"],
    features: ["Lake Views", "Brewery", "Pool", "Entertainment Area"],
  },

  // Wyoming
  {
    id: "search_wy_1",
    type: "property",
    title: "Jackson Hole Ski Estate",
    subtitle: "Jackson Hole, WY • Mountain Resort • $18.5M",
    address: "654 Jackson Hole Ski Estate",
    city: "Jackson Hole",
    state: "WY",
    zipCode: "83025",
    value: 18500000,
    ownerName: "Mountain Holdings Corporation",
    ownerWealth: 650000000,
    propertyType: "lodge",
    coordinates: { lat: 43.4799, lng: -110.7624 },
    bedrooms: 8,
    bathrooms: 9,
    sqft: 16000,
    images: ["/placeholder.svg?height=300&width=400&text=Jackson+Hole+Ski+Estate"],
    features: ["Ski Access", "Mountain Views", "Hot Tub", "Guest Lodge"],
  },

  // Washington DC
  {
    id: "search_dc_1",
    type: "property",
    title: "Georgetown Political Estate",
    subtitle: "Washington, DC • Political Elite • $15.8M",
    address: "987 Georgetown Political Estate",
    city: "Washington",
    state: "DC",
    zipCode: "20007",
    value: 15800000,
    ownerName: "Political Dynasty Holdings",
    ownerWealth: 485000000,
    propertyType: "mansion",
    coordinates: { lat: 38.9072, lng: -77.0369 },
    bedrooms: 8,
    bathrooms: 10,
    sqft: 14500,
    images: ["/placeholder.svg?height=300&width=400&text=Georgetown+Political+Estate"],
    features: ["Historic Architecture", "Security System", "Wine Cellar", "Home Office"],
  },
]

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const query = searchParams.get("q") || ""
    const type = searchParams.get("type") || "all"
    const minValue = searchParams.get("minValue") ? Number.parseInt(searchParams.get("minValue")!) : undefined
    const maxValue = searchParams.get("maxValue") ? Number.parseInt(searchParams.get("maxValue")!) : undefined
    const location = searchParams.get("location") || ""
    const propertyType = searchParams.get("propertyType") || ""
    const ownerType = searchParams.get("ownerType") || ""

    console.log("🔍 Search API request:", {
      query,
      type,
      minValue,
      maxValue,
      location,
      propertyType,
      ownerType,
    })

    // Filter sample properties based on search criteria
    const results = sampleProperties.filter((property) => {
      // Query filter
      if (query) {
        const queryLower = query.toLowerCase()
        const titleMatch = property.title.toLowerCase().includes(queryLower)
        const cityMatch = property.city.toLowerCase().includes(queryLower)
        const stateMatch = property.state.toLowerCase().includes(queryLower)
        const ownerMatch = property.ownerName.toLowerCase().includes(queryLower)
        if (!titleMatch && !cityMatch && !stateMatch && !ownerMatch) return false
      }

      // Value range filter
      if (minValue && property.value < minValue) return false
      if (maxValue && property.value > maxValue) return false

      // Property type filter
      if (propertyType && propertyType !== "all") {
        if (!property.propertyType.toLowerCase().includes(propertyType.toLowerCase())) return false
      }

      // Location filter
      if (location) {
        const locationLower = location.toLowerCase()
        const cityMatch = property.city.toLowerCase().includes(locationLower)
        const stateMatch = property.state.toLowerCase().includes(locationLower)
        if (!cityMatch && !stateMatch) return false
      }

      return true
    })

    // Sort by value (highest first)
    results.sort((a, b) => b.value - a.value)

    console.log("📊 Search completed:", {
      query,
      filtersUsed: [minValue, maxValue, propertyType, location].filter(Boolean).length,
      resultsFound: results.length,
      sampleResult: results[0]
        ? {
            title: results[0].title,
            value: results[0].value,
          }
        : null,
    })

    return NextResponse.json({
      results: results,
      total: results.length,
      cached: false,
      query,
      filters: { minValue, maxValue, propertyType, location },
      timestamp: new Date().toISOString(),
      dataSource: "mock_data_all_states",
      message: "Using comprehensive mock data for all US states",
    })
  } catch (error) {
    console.error("❌ Search API error:", {
      message: error instanceof Error ? error.message : "Unknown error",
      stack: error instanceof Error ? error.stack : undefined,
    })

    // Return sample data instead of error
    return NextResponse.json({
      results: sampleProperties.slice(0, 3),
      total: 3,
      cached: false,
      mock: true,
      error: "Search service using mock data for all states",
      timestamp: new Date().toISOString(),
      dataSource: "mock_data_all_states",
    })
  }
}
