import { type NextRequest, NextResponse } from "next/server"

// Comprehensive property data for all 50 states + DC
const ALL_US_PROPERTIES = [
  // ALABAMA
  {
    id: "prop_alabama_1",
    title: "Historic Antebellum Mansion",
    subtitle: "Montgomery, Alabama Estate",
    location: "Montgomery, AL",
    value: 2800000,
    owner: "Southern Heritage Trust",
    ownerWealth: 45000000,
    type: "property",
    state: "Alabama",
    coordinates: { lat: 32.3617, lng: -86.2792 },
  },
  {
    id: "prop_alabama_2",
    title: "Gulf Coast Waterfront Estate",
    subtitle: "Mobile Bay Luxury Home",
    location: "Mobile, AL",
    value: 3200000,
    owner: "Coastal Development LLC",
    ownerWealth: 38000000,
    type: "property",
    state: "Alabama",
    coordinates: { lat: 30.6944, lng: -88.0431 },
  },

  // ALASKA
  {
    id: "prop_alaska_1",
    title: "Wilderness Lodge & Estate",
    subtitle: "Anchorage Mountain Retreat",
    location: "Anchorage, AK",
    value: 4500000,
    owner: "Arctic Holdings Corp",
    ownerWealth: 85000000,
    type: "property",
    state: "Alaska",
    coordinates: { lat: 61.2181, lng: -149.9003 },
  },
  {
    id: "prop_alaska_2",
    title: "Luxury Ski Chalet",
    subtitle: "Girdwood Alpine Estate",
    location: "Girdwood, AK",
    value: 3800000,
    owner: "Northern Investments",
    ownerWealth: 62000000,
    type: "property",
    state: "Alaska",
    coordinates: { lat: 60.9428, lng: -149.1661 },
  },

  // ARIZONA
  {
    id: "prop_arizona_1",
    title: "Desert Mountain Mansion",
    subtitle: "Scottsdale Luxury Estate",
    location: "Scottsdale, AZ",
    value: 7200000,
    owner: "Desert Luxury Holdings",
    ownerWealth: 125000000,
    type: "property",
    state: "Arizona",
    coordinates: { lat: 33.4942, lng: -111.9261 },
  },
  {
    id: "prop_arizona_2",
    title: "Phoenix Penthouse",
    subtitle: "Downtown High-Rise Condo",
    location: "Phoenix, AZ",
    value: 2900000,
    owner: "Southwest Real Estate Mogul",
    ownerWealth: 78000000,
    type: "property",
    state: "Arizona",
    coordinates: { lat: 33.4484, lng: -112.074 },
  },

  // ARKANSAS
  {
    id: "prop_arkansas_1",
    title: "Ozark Mountain Estate",
    subtitle: "Bentonville Corporate Retreat",
    location: "Bentonville, AR",
    value: 4200000,
    owner: "Retail Dynasty Holdings",
    ownerWealth: 95000000,
    type: "property",
    state: "Arkansas",
    coordinates: { lat: 36.3729, lng: -94.2088 },
  },
  {
    id: "prop_arkansas_2",
    title: "Little Rock Riverfront Mansion",
    subtitle: "Arkansas River Estate",
    location: "Little Rock, AR",
    value: 2100000,
    owner: "Arkansas Investment Group",
    ownerWealth: 42000000,
    type: "property",
    state: "Arkansas",
    coordinates: { lat: 34.7465, lng: -92.2896 },
  },

  // CALIFORNIA
  {
    id: "prop_california_1",
    title: "Beverly Hills Mega Mansion",
    subtitle: "Rodeo Drive Estate",
    location: "Beverly Hills, CA",
    value: 25000000,
    owner: "Entertainment Mogul Inc",
    ownerWealth: 450000000,
    type: "property",
    state: "California",
    coordinates: { lat: 34.0736, lng: -118.4004 },
  },
  {
    id: "prop_california_2",
    title: "Malibu Oceanfront Estate",
    subtitle: "Pacific Coast Highway Mansion",
    location: "Malibu, CA",
    value: 18500000,
    owner: "Celebrity Holdings Trust",
    ownerWealth: 320000000,
    type: "property",
    state: "California",
    coordinates: { lat: 34.0259, lng: -118.7798 },
  },
  {
    id: "prop_california_3",
    title: "Silicon Valley Tech Mansion",
    subtitle: "Palo Alto Innovation Estate",
    location: "Palo Alto, CA",
    value: 12800000,
    owner: "Tech Billionaire LLC",
    ownerWealth: 2800000000,
    type: "property",
    state: "California",
    coordinates: { lat: 37.4419, lng: -122.143 },
  },
  {
    id: "prop_california_4",
    title: "San Francisco Penthouse",
    subtitle: "Nob Hill Luxury Condo",
    location: "San Francisco, CA",
    value: 8900000,
    owner: "Bay Area Ventures",
    ownerWealth: 185000000,
    type: "property",
    state: "California",
    coordinates: { lat: 37.7749, lng: -122.4194 },
  },

  // COLORADO
  {
    id: "prop_colorado_1",
    title: "Aspen Ski Lodge",
    subtitle: "Mountain Resort Estate",
    location: "Aspen, CO",
    value: 15200000,
    owner: "Alpine Holdings Group",
    ownerWealth: 280000000,
    type: "property",
    state: "Colorado",
    coordinates: { lat: 39.1911, lng: -106.8175 },
  },
  {
    id: "prop_colorado_2",
    title: "Denver Tech Hub Penthouse",
    subtitle: "Downtown Innovation District",
    location: "Denver, CO",
    value: 3800000,
    owner: "Rocky Mountain Ventures",
    ownerWealth: 92000000,
    type: "property",
    state: "Colorado",
    coordinates: { lat: 39.7392, lng: -104.9903 },
  },

  // CONNECTICUT
  {
    id: "prop_connecticut_1",
    title: "Greenwich Hedge Fund Estate",
    subtitle: "Gold Coast Mansion",
    location: "Greenwich, CT",
    value: 12500000,
    owner: "Wall Street Titan",
    ownerWealth: 650000000,
    type: "property",
    state: "Connecticut",
    coordinates: { lat: 41.0534, lng: -73.5387 },
  },
  {
    id: "prop_connecticut_2",
    title: "Fairfield County Estate",
    subtitle: "New Canaan Luxury Home",
    location: "New Canaan, CT",
    value: 8900000,
    owner: "Private Equity Partners",
    ownerWealth: 420000000,
    type: "property",
    state: "Connecticut",
    coordinates: { lat: 41.1468, lng: -73.4948 },
  },

  // DELAWARE
  {
    id: "prop_delaware_1",
    title: "Wilmington Corporate Estate",
    subtitle: "DuPont Legacy Mansion",
    location: "Wilmington, DE",
    value: 4200000,
    owner: "Chemical Dynasty Trust",
    ownerWealth: 180000000,
    type: "property",
    state: "Delaware",
    coordinates: { lat: 39.7391, lng: -75.5398 },
  },
  {
    id: "prop_delaware_2",
    title: "Rehoboth Beach Estate",
    subtitle: "Delaware Shore Mansion",
    location: "Rehoboth Beach, DE",
    value: 3800000,
    owner: "Coastal Holdings LLC",
    ownerWealth: 85000000,
    type: "property",
    state: "Delaware",
    coordinates: { lat: 38.7198, lng: -75.076 },
  },

  // FLORIDA
  {
    id: "prop_florida_1",
    title: "Miami Beach Penthouse",
    subtitle: "South Beach Luxury Condo",
    location: "Miami Beach, FL",
    value: 9800000,
    owner: "International Real Estate Mogul",
    ownerWealth: 340000000,
    type: "property",
    state: "Florida",
    coordinates: { lat: 25.7907, lng: -80.13 },
  },
  {
    id: "prop_florida_2",
    title: "Naples Waterfront Estate",
    subtitle: "Gulf Coast Mansion",
    location: "Naples, FL",
    value: 7200000,
    owner: "Sunshine State Holdings",
    ownerWealth: 165000000,
    type: "property",
    state: "Florida",
    coordinates: { lat: 26.142, lng: -81.7948 },
  },
  {
    id: "prop_florida_3",
    title: "Orlando Theme Park Estate",
    subtitle: "Entertainment District Mansion",
    location: "Orlando, FL",
    value: 4500000,
    owner: "Entertainment Empire LLC",
    ownerWealth: 125000000,
    type: "property",
    state: "Florida",
    coordinates: { lat: 28.5383, lng: -81.3792 },
  },

  // GEORGIA
  {
    id: "prop_georgia_1",
    title: "Atlanta Buckhead Mansion",
    subtitle: "Peachtree Elite Estate",
    location: "Atlanta, GA",
    value: 6800000,
    owner: "Southern Capital Group",
    ownerWealth: 195000000,
    type: "property",
    state: "Georgia",
    coordinates: { lat: 33.8688, lng: -84.3717 },
  },
  {
    id: "prop_georgia_2",
    title: "Savannah Historic Estate",
    subtitle: "Garden District Mansion",
    location: "Savannah, GA",
    value: 3200000,
    owner: "Historic Preservation Trust",
    ownerWealth: 78000000,
    type: "property",
    state: "Georgia",
    coordinates: { lat: 32.0835, lng: -81.0998 },
  },

  // HAWAII
  {
    id: "prop_hawaii_1",
    title: "Maui Oceanfront Estate",
    subtitle: "Wailea Luxury Resort Home",
    location: "Wailea, HI",
    value: 22000000,
    owner: "Pacific Paradise Holdings",
    ownerWealth: 580000000,
    type: "property",
    state: "Hawaii",
    coordinates: { lat: 20.6947, lng: -156.4444 },
  },
  {
    id: "prop_hawaii_2",
    title: "Oahu Diamond Head Estate",
    subtitle: "Honolulu Luxury Mansion",
    location: "Honolulu, HI",
    value: 15800000,
    owner: "Island Investment Group",
    ownerWealth: 420000000,
    type: "property",
    state: "Hawaii",
    coordinates: { lat: 21.3099, lng: -157.8581 },
  },

  // IDAHO
  {
    id: "prop_idaho_1",
    title: "Sun Valley Ski Estate",
    subtitle: "Mountain Resort Mansion",
    location: "Sun Valley, ID",
    value: 8500000,
    owner: "Mountain Holdings Corp",
    ownerWealth: 185000000,
    type: "property",
    state: "Idaho",
    coordinates: { lat: 43.6963, lng: -114.3574 },
  },
  {
    id: "prop_idaho_2",
    title: "Boise Tech Executive Estate",
    subtitle: "Foothills Luxury Home",
    location: "Boise, ID",
    value: 2800000,
    owner: "Northwest Technology Ventures",
    ownerWealth: 95000000,
    type: "property",
    state: "Idaho",
    coordinates: { lat: 43.615, lng: -116.2023 },
  },

  // ILLINOIS
  {
    id: "prop_illinois_1",
    title: "Chicago Gold Coast Penthouse",
    subtitle: "Lake Michigan Luxury Condo",
    location: "Chicago, IL",
    value: 8900000,
    owner: "Windy City Holdings",
    ownerWealth: 285000000,
    type: "property",
    state: "Illinois",
    coordinates: { lat: 41.8986, lng: -87.6233 },
  },
  {
    id: "prop_illinois_2",
    title: "Lake Forest Estate",
    subtitle: "North Shore Mansion",
    location: "Lake Forest, IL",
    value: 5200000,
    owner: "Great Lakes Investment Group",
    ownerWealth: 145000000,
    type: "property",
    state: "Illinois",
    coordinates: { lat: 42.2587, lng: -87.8406 },
  },

  // INDIANA
  {
    id: "prop_indiana_1",
    title: "Indianapolis Racing Estate",
    subtitle: "Speedway District Mansion",
    location: "Indianapolis, IN",
    value: 3200000,
    owner: "Motorsports Holdings LLC",
    ownerWealth: 85000000,
    type: "property",
    state: "Indiana",
    coordinates: { lat: 39.7684, lng: -86.1581 },
  },
  {
    id: "prop_indiana_2",
    title: "Carmel Executive Estate",
    subtitle: "Hamilton County Luxury Home",
    location: "Carmel, IN",
    value: 2800000,
    owner: "Midwest Manufacturing Mogul",
    ownerWealth: 125000000,
    type: "property",
    state: "Indiana",
    coordinates: { lat: 39.9784, lng: -86.118 },
  },

  // IOWA
  {
    id: "prop_iowa_1",
    title: "Des Moines Insurance Empire Estate",
    subtitle: "West Des Moines Mansion",
    location: "West Des Moines, IA",
    value: 2400000,
    owner: "Insurance Dynasty Holdings",
    ownerWealth: 95000000,
    type: "property",
    state: "Iowa",
    coordinates: { lat: 41.5868, lng: -93.7112 },
  },
  {
    id: "prop_iowa_2",
    title: "Iowa City Academic Estate",
    subtitle: "University District Mansion",
    location: "Iowa City, IA",
    value: 1800000,
    owner: "Educational Holdings Trust",
    ownerWealth: 45000000,
    type: "property",
    state: "Iowa",
    coordinates: { lat: 41.6611, lng: -91.5302 },
  },

  // KANSAS
  {
    id: "prop_kansas_1",
    title: "Kansas City Agricultural Estate",
    subtitle: "Prairie Luxury Mansion",
    location: "Kansas City, KS",
    value: 2800000,
    owner: "Agricultural Investment Group",
    ownerWealth: 125000000,
    type: "property",
    state: "Kansas",
    coordinates: { lat: 39.1142, lng: -94.6275 },
  },
  {
    id: "prop_kansas_2",
    title: "Wichita Aviation Estate",
    subtitle: "Aircraft Manufacturing Mansion",
    location: "Wichita, KS",
    value: 2200000,
    owner: "Aviation Holdings Corp",
    ownerWealth: 85000000,
    type: "property",
    state: "Kansas",
    coordinates: { lat: 37.6872, lng: -97.3301 },
  },

  // KENTUCKY
  {
    id: "prop_kentucky_1",
    title: "Louisville Bourbon Estate",
    subtitle: "Kentucky Derby District Mansion",
    location: "Louisville, KY",
    value: 3800000,
    owner: "Bourbon Dynasty Holdings",
    ownerWealth: 165000000,
    type: "property",
    state: "Kentucky",
    coordinates: { lat: 38.2527, lng: -85.7585 },
  },
  {
    id: "prop_kentucky_2",
    title: "Lexington Horse Farm Estate",
    subtitle: "Bluegrass Thoroughbred Ranch",
    location: "Lexington, KY",
    value: 4200000,
    owner: "Equestrian Holdings LLC",
    ownerWealth: 125000000,
    type: "property",
    state: "Kentucky",
    coordinates: { lat: 38.0406, lng: -84.5037 },
  },

  // LOUISIANA
  {
    id: "prop_louisiana_1",
    title: "New Orleans Garden District Mansion",
    subtitle: "French Quarter Elite Estate",
    location: "New Orleans, LA",
    value: 4500000,
    owner: "Creole Heritage Trust",
    ownerWealth: 145000000,
    type: "property",
    state: "Louisiana",
    coordinates: { lat: 29.9511, lng: -90.0715 },
  },
  {
    id: "prop_louisiana_2",
    title: "Baton Rouge Petroleum Estate",
    subtitle: "Oil Industry Mansion",
    location: "Baton Rouge, LA",
    value: 3200000,
    owner: "Energy Holdings Corporation",
    ownerWealth: 285000000,
    type: "property",
    state: "Louisiana",
    coordinates: { lat: 30.4515, lng: -91.1871 },
  },

  // MAINE
  {
    id: "prop_maine_1",
    title: "Bar Harbor Coastal Estate",
    subtitle: "Acadia National Park Mansion",
    location: "Bar Harbor, ME",
    value: 6800000,
    owner: "New England Maritime Holdings",
    ownerWealth: 185000000,
    type: "property",
    state: "Maine",
    coordinates: { lat: 44.3876, lng: -68.2039 },
  },
  {
    id: "prop_maine_2",
    title: "Portland Lobster Empire Estate",
    subtitle: "Casco Bay Waterfront Mansion",
    location: "Portland, ME",
    value: 3800000,
    owner: "Seafood Dynasty LLC",
    ownerWealth: 95000000,
    type: "property",
    state: "Maine",
    coordinates: { lat: 43.6591, lng: -70.2568 },
  },

  // MARYLAND
  {
    id: "prop_maryland_1",
    title: "Potomac Political Estate",
    subtitle: "Washington DC Suburb Mansion",
    location: "Potomac, MD",
    value: 8500000,
    owner: "Beltway Holdings Group",
    ownerWealth: 285000000,
    type: "property",
    state: "Maryland",
    coordinates: { lat: 39.0458, lng: -77.2086 },
  },
  {
    id: "prop_maryland_2",
    title: "Annapolis Naval Estate",
    subtitle: "Chesapeake Bay Mansion",
    location: "Annapolis, MD",
    value: 4200000,
    owner: "Maritime Holdings Trust",
    ownerWealth: 125000000,
    type: "property",
    state: "Maryland",
    coordinates: { lat: 38.9784, lng: -76.5951 },
  },

  // MASSACHUSETTS
  {
    id: "prop_massachusetts_1",
    title: "Boston Beacon Hill Mansion",
    subtitle: "Historic Back Bay Estate",
    location: "Boston, MA",
    value: 12500000,
    owner: "New England Dynasty Holdings",
    ownerWealth: 485000000,
    type: "property",
    state: "Massachusetts",
    coordinates: { lat: 42.3601, lng: -71.0589 },
  },
  {
    id: "prop_massachusetts_2",
    title: "Martha's Vineyard Estate",
    subtitle: "Island Summer Mansion",
    location: "Martha's Vineyard, MA",
    value: 18500000,
    owner: "Island Holdings Corporation",
    ownerWealth: 650000000,
    type: "property",
    state: "Massachusetts",
    coordinates: { lat: 41.3888, lng: -70.6761 },
  },

  // MICHIGAN
  {
    id: "prop_michigan_1",
    title: "Detroit Automotive Estate",
    subtitle: "Motor City Executive Mansion",
    location: "Detroit, MI",
    value: 3800000,
    owner: "Automotive Dynasty Holdings",
    ownerWealth: 285000000,
    type: "property",
    state: "Michigan",
    coordinates: { lat: 42.3314, lng: -83.0458 },
  },
  {
    id: "prop_michigan_2",
    title: "Traverse City Vineyard Estate",
    subtitle: "Great Lakes Wine Country Mansion",
    location: "Traverse City, MI",
    value: 2800000,
    owner: "Great Lakes Vineyards LLC",
    ownerWealth: 85000000,
    type: "property",
    state: "Michigan",
    coordinates: { lat: 44.7631, lng: -85.6206 },
  },

  // MINNESOTA
  {
    id: "prop_minnesota_1",
    title: "Minneapolis Lake Estate",
    subtitle: "Chain of Lakes Mansion",
    location: "Minneapolis, MN",
    value: 4200000,
    owner: "Twin Cities Holdings Group",
    ownerWealth: 165000000,
    type: "property",
    state: "Minnesota",
    coordinates: { lat: 44.9778, lng: -93.265 },
  },
  {
    id: "prop_minnesota_2",
    title: "Duluth Shipping Estate",
    subtitle: "Lake Superior Mansion",
    location: "Duluth, MN",
    value: 2400000,
    owner: "Great Lakes Shipping Corp",
    ownerWealth: 125000000,
    type: "property",
    state: "Minnesota",
    coordinates: { lat: 46.7867, lng: -92.1005 },
  },

  // MISSISSIPPI
  {
    id: "prop_mississippi_1",
    title: "Jackson Cotton Estate",
    subtitle: "Antebellum Plantation Mansion",
    location: "Jackson, MS",
    value: 2800000,
    owner: "Southern Agriculture Holdings",
    ownerWealth: 95000000,
    type: "property",
    state: "Mississippi",
    coordinates: { lat: 32.2988, lng: -90.1848 },
  },
  {
    id: "prop_mississippi_2",
    title: "Biloxi Casino Estate",
    subtitle: "Gulf Coast Gaming Mansion",
    location: "Biloxi, MS",
    value: 3200000,
    owner: "Gaming Empire LLC",
    ownerWealth: 185000000,
    type: "property",
    state: "Mississippi",
    coordinates: { lat: 30.396, lng: -88.8853 },
  },

  // MISSOURI
  {
    id: "prop_missouri_1",
    title: "St. Louis Brewing Estate",
    subtitle: "Gateway Arch District Mansion",
    location: "St. Louis, MO",
    value: 3800000,
    owner: "Brewing Dynasty Holdings",
    ownerWealth: 285000000,
    type: "property",
    state: "Missouri",
    coordinates: { lat: 38.627, lng: -90.1994 },
  },
  {
    id: "prop_missouri_2",
    title: "Kansas City BBQ Empire Estate",
    subtitle: "Jazz District Mansion",
    location: "Kansas City, MO",
    value: 2800000,
    owner: "Hospitality Holdings Group",
    ownerWealth: 125000000,
    type: "property",
    state: "Missouri",
    coordinates: { lat: 39.0997, lng: -94.5786 },
  },

  // MONTANA
  {
    id: "prop_montana_1",
    title: "Big Sky Ranch Estate",
    subtitle: "Yellowstone Gateway Mansion",
    location: "Big Sky, MT",
    value: 12500000,
    owner: "Mountain Ranch Holdings",
    ownerWealth: 485000000,
    type: "property",
    state: "Montana",
    coordinates: { lat: 45.2849, lng: -111.4083 },
  },
  {
    id: "prop_montana_2",
    title: "Billings Energy Estate",
    subtitle: "Oil & Gas Executive Mansion",
    location: "Billings, MT",
    value: 2400000,
    owner: "Energy Holdings Corporation",
    ownerWealth: 165000000,
    type: "property",
    state: "Montana",
    coordinates: { lat: 45.7833, lng: -108.5007 },
  },

  // NEBRASKA
  {
    id: "prop_nebraska_1",
    title: "Omaha Investment Estate",
    subtitle: "Warren Buffett District Mansion",
    location: "Omaha, NE",
    value: 3200000,
    owner: "Investment Holdings Group",
    ownerWealth: 285000000,
    type: "property",
    state: "Nebraska",
    coordinates: { lat: 41.2565, lng: -95.9345 },
  },
  {
    id: "prop_nebraska_2",
    title: "Lincoln Agricultural Estate",
    subtitle: "Cornhusker State Mansion",
    location: "Lincoln, NE",
    value: 1800000,
    owner: "Agricultural Holdings LLC",
    ownerWealth: 85000000,
    type: "property",
    state: "Nebraska",
    coordinates: { lat: 40.8136, lng: -96.7026 },
  },

  // NEVADA
  {
    id: "prop_nevada_1",
    title: "Las Vegas Casino Estate",
    subtitle: "Strip View Penthouse",
    location: "Las Vegas, NV",
    value: 15800000,
    owner: "Gaming Empire Holdings",
    ownerWealth: 650000000,
    type: "property",
    state: "Nevada",
    coordinates: { lat: 36.1699, lng: -115.1398 },
  },
  {
    id: "prop_nevada_2",
    title: "Lake Tahoe Alpine Estate",
    subtitle: "Sierra Nevada Mansion",
    location: "Lake Tahoe, NV",
    value: 8500000,
    owner: "Alpine Holdings Corporation",
    ownerWealth: 285000000,
    type: "property",
    state: "Nevada",
    coordinates: { lat: 39.0968, lng: -120.0324 },
  },

  // NEW HAMPSHIRE
  {
    id: "prop_newhampshire_1",
    title: "White Mountains Estate",
    subtitle: "Presidential Range Mansion",
    location: "North Conway, NH",
    value: 4200000,
    owner: "Mountain Holdings Trust",
    ownerWealth: 125000000,
    type: "property",
    state: "New Hampshire",
    coordinates: { lat: 44.0542, lng: -71.1253 },
  },
  {
    id: "prop_newhampshire_2",
    title: "Portsmouth Maritime Estate",
    subtitle: "Seacoast Historic Mansion",
    location: "Portsmouth, NH",
    value: 3800000,
    owner: "Maritime Holdings LLC",
    ownerWealth: 95000000,
    type: "property",
    state: "New Hampshire",
    coordinates: { lat: 43.0718, lng: -70.7626 },
  },

  // NEW JERSEY
  {
    id: "prop_newjersey_1",
    title: "Princeton University Estate",
    subtitle: "Ivy League District Mansion",
    location: "Princeton, NJ",
    value: 6800000,
    owner: "Academic Holdings Group",
    ownerWealth: 285000000,
    type: "property",
    state: "New Jersey",
    coordinates: { lat: 40.3573, lng: -74.6672 },
  },
  {
    id: "prop_newjersey_2",
    title: "Atlantic City Boardwalk Estate",
    subtitle: "Casino District Penthouse",
    location: "Atlantic City, NJ",
    value: 4200000,
    owner: "Gaming Holdings Corporation",
    ownerWealth: 185000000,
    type: "property",
    state: "New Jersey",
    coordinates: { lat: 39.3643, lng: -74.4229 },
  },

  // NEW MEXICO
  {
    id: "prop_newmexico_1",
    title: "Santa Fe Adobe Estate",
    subtitle: "Desert Art District Mansion",
    location: "Santa Fe, NM",
    value: 3800000,
    owner: "Southwest Art Holdings",
    ownerWealth: 125000000,
    type: "property",
    state: "New Mexico",
    coordinates: { lat: 35.687, lng: -105.9378 },
  },
  {
    id: "prop_newmexico_2",
    title: "Albuquerque Tech Estate",
    subtitle: "High Desert Innovation Mansion",
    location: "Albuquerque, NM",
    value: 2400000,
    owner: "Desert Technology Ventures",
    ownerWealth: 85000000,
    type: "property",
    state: "New Mexico",
    coordinates: { lat: 35.0844, lng: -106.6504 },
  },

  // NEW YORK
  {
    id: "prop_newyork_1",
    title: "Manhattan Penthouse",
    subtitle: "Central Park West Luxury",
    location: "Manhattan, NY",
    value: 28500000,
    owner: "Wall Street Titan",
    ownerWealth: 1200000000,
    type: "property",
    state: "New York",
    coordinates: { lat: 40.7614, lng: -73.9776 },
  },
  {
    id: "prop_newyork_2",
    title: "Hamptons Summer Estate",
    subtitle: "East Hampton Oceanfront",
    location: "East Hampton, NY",
    value: 22000000,
    owner: "Real Estate Dynasty",
    ownerWealth: 850000000,
    type: "property",
    state: "New York",
    coordinates: { lat: 40.9629, lng: -72.1989 },
  },
  {
    id: "prop_newyork_3",
    title: "Hudson Valley Estate",
    subtitle: "Upstate Luxury Retreat",
    location: "Hudson Valley, NY",
    value: 8500000,
    owner: "Media Mogul Holdings",
    ownerWealth: 485000000,
    type: "property",
    state: "New York",
    coordinates: { lat: 42.2506, lng: -73.7845 },
  },

  // NORTH CAROLINA
  {
    id: "prop_northcarolina_1",
    title: "Charlotte Banking Estate",
    subtitle: "Financial District Mansion",
    location: "Charlotte, NC",
    value: 4800000,
    owner: "Banking Dynasty Holdings",
    ownerWealth: 285000000,
    type: "property",
    state: "North Carolina",
    coordinates: { lat: 35.2271, lng: -80.8431 },
  },
  {
    id: "prop_northcarolina_2",
    title: "Outer Banks Beach Estate",
    subtitle: "Atlantic Coast Mansion",
    location: "Outer Banks, NC",
    value: 6200000,
    owner: "Coastal Holdings LLC",
    ownerWealth: 165000000,
    type: "property",
    state: "North Carolina",
    coordinates: { lat: 35.5582, lng: -75.4665 },
  },

  // NORTH DAKOTA
  {
    id: "prop_northdakota_1",
    title: "Fargo Agricultural Estate",
    subtitle: "Red River Valley Mansion",
    location: "Fargo, ND",
    value: 1800000,
    owner: "Agricultural Holdings Group",
    ownerWealth: 85000000,
    type: "property",
    state: "North Dakota",
    coordinates: { lat: 46.8772, lng: -96.7898 },
  },
  {
    id: "prop_northdakota_2",
    title: "Bismarck Energy Estate",
    subtitle: "Oil Boom Executive Mansion",
    location: "Bismarck, ND",
    value: 2200000,
    owner: "Energy Holdings Corporation",
    ownerWealth: 165000000,
    type: "property",
    state: "North Dakota",
    coordinates: { lat: 46.8083, lng: -100.7837 },
  },

  // OHIO
  {
    id: "prop_ohio_1",
    title: "Cleveland Industrial Estate",
    subtitle: "Lake Erie Mansion",
    location: "Cleveland, OH",
    value: 3800000,
    owner: "Industrial Holdings Group",
    ownerWealth: 185000000,
    type: "property",
    state: "Ohio",
    coordinates: { lat: 41.4993, lng: -81.6944 },
  },
  {
    id: "prop_ohio_2",
    title: "Columbus Tech Estate",
    subtitle: "Innovation District Mansion",
    location: "Columbus, OH",
    value: 2800000,
    owner: "Midwest Technology Ventures",
    ownerWealth: 125000000,
    type: "property",
    state: "Ohio",
    coordinates: { lat: 39.9612, lng: -82.9988 },
  },

  // OKLAHOMA
  {
    id: "prop_oklahoma_1",
    title: "Oklahoma City Oil Estate",
    subtitle: "Energy Capital Mansion",
    location: "Oklahoma City, OK",
    value: 3200000,
    owner: "Oil Dynasty Holdings",
    ownerWealth: 285000000,
    type: "property",
    state: "Oklahoma",
    coordinates: { lat: 35.4676, lng: -97.5164 },
  },
  {
    id: "prop_oklahoma_2",
    title: "Tulsa Aviation Estate",
    subtitle: "Aerospace Industry Mansion",
    location: "Tulsa, OK",
    value: 2400000,
    owner: "Aviation Holdings Corporation",
    ownerWealth: 125000000,
    type: "property",
    state: "Oklahoma",
    coordinates: { lat: 36.154, lng: -95.9928 },
  },

  // OREGON
  {
    id: "prop_oregon_1",
    title: "Portland Tech Estate",
    subtitle: "Silicon Forest Mansion",
    location: "Portland, OR",
    value: 4800000,
    owner: "Pacific Northwest Ventures",
    ownerWealth: 185000000,
    type: "property",
    state: "Oregon",
    coordinates: { lat: 45.5152, lng: -122.6784 },
  },
  {
    id: "prop_oregon_2",
    title: "Bend Resort Estate",
    subtitle: "Cascade Mountains Mansion",
    location: "Bend, OR",
    value: 3800000,
    owner: "Mountain Holdings LLC",
    ownerWealth: 125000000,
    type: "property",
    state: "Oregon",
    coordinates: { lat: 44.0582, lng: -121.3153 },
  },

  // PENNSYLVANIA
  {
    id: "prop_pennsylvania_1",
    title: "Philadelphia Historic Estate",
    subtitle: "Main Line Mansion",
    location: "Philadelphia, PA",
    value: 6800000,
    owner: "Colonial Holdings Trust",
    ownerWealth: 285000000,
    type: "property",
    state: "Pennsylvania",
    coordinates: { lat: 39.9526, lng: -75.1652 },
  },
  {
    id: "prop_pennsylvania_2",
    title: "Pittsburgh Steel Estate",
    subtitle: "Three Rivers Mansion",
    location: "Pittsburgh, PA",
    value: 3200000,
    owner: "Steel Dynasty Holdings",
    ownerWealth: 185000000,
    type: "property",
    state: "Pennsylvania",
    coordinates: { lat: 40.4406, lng: -79.9959 },
  },

  // RHODE ISLAND
  {
    id: "prop_rhodeisland_1",
    title: "Newport Gilded Age Mansion",
    subtitle: "Ocean Drive Estate",
    location: "Newport, RI",
    value: 18500000,
    owner: "New England Dynasty",
    ownerWealth: 650000000,
    type: "property",
    state: "Rhode Island",
    coordinates: { lat: 41.4901, lng: -71.3128 },
  },
  {
    id: "prop_rhodeisland_2",
    title: "Providence Banking Estate",
    subtitle: "Federal Hill Mansion",
    location: "Providence, RI",
    value: 4200000,
    owner: "Banking Holdings Group",
    ownerWealth: 125000000,
    type: "property",
    state: "Rhode Island",
    coordinates: { lat: 41.824, lng: -71.4128 },
  },

  // SOUTH CAROLINA
  {
    id: "prop_southcarolina_1",
    title: "Charleston Historic Estate",
    subtitle: "Rainbow Row Mansion",
    location: "Charleston, SC",
    value: 5800000,
    owner: "Southern Heritage Holdings",
    ownerWealth: 185000000,
    type: "property",
    state: "South Carolina",
    coordinates: { lat: 32.7767, lng: -79.9311 },
  },
  {
    id: "prop_southcarolina_2",
    title: "Hilton Head Resort Estate",
    subtitle: "Sea Island Mansion",
    location: "Hilton Head, SC",
    value: 4200000,
    owner: "Coastal Resort Holdings",
    ownerWealth: 125000000,
    type: "property",
    state: "South Carolina",
    coordinates: { lat: 32.2163, lng: -80.7526 },
  },

  // SOUTH DAKOTA
  {
    id: "prop_southdakota_1",
    title: "Rapid City Mining Estate",
    subtitle: "Black Hills Mansion",
    location: "Rapid City, SD",
    value: 2200000,
    owner: "Mining Holdings Corporation",
    ownerWealth: 125000000,
    type: "property",
    state: "South Dakota",
    coordinates: { lat: 44.0805, lng: -103.231 },
  },
  {
    id: "prop_southdakota_2",
    title: "Sioux Falls Banking Estate",
    subtitle: "Financial District Mansion",
    location: "Sioux Falls, SD",
    value: 1800000,
    owner: "Regional Banking Group",
    ownerWealth: 85000000,
    type: "property",
    state: "South Dakota",
    coordinates: { lat: 43.546, lng: -96.7313 },
  },

  // TENNESSEE
  {
    id: "prop_tennessee_1",
    title: "Nashville Music Estate",
    subtitle: "Music Row Mansion",
    location: "Nashville, TN",
    value: 6800000,
    owner: "Music Industry Holdings",
    ownerWealth: 285000000,
    type: "property",
    state: "Tennessee",
    coordinates: { lat: 36.1627, lng: -86.7816 },
  },
  {
    id: "prop_tennessee_2",
    title: "Memphis Blues Estate",
    subtitle: "Beale Street District Mansion",
    location: "Memphis, TN",
    value: 3200000,
    owner: "Entertainment Holdings LLC",
    type: "property",
    state: "Tennessee",
    coordinates: { lat: 35.1495, lng: -90.049 },
  },

  // TEXAS
  {
    id: "prop_texas_1",
    title: "Dallas Oil Empire Estate",
    subtitle: "Highland Park Mansion",
    location: "Dallas, TX",
    value: 12500000,
    owner: "Texas Oil Dynasty",
    ownerWealth: 850000000,
    type: "property",
    state: "Texas",
    coordinates: { lat: 32.7767, lng: -96.797 },
  },
  {
    id: "prop_texas_2",
    title: "Houston Energy Estate",
    subtitle: "River Oaks Mansion",
    location: "Houston, TX",
    value: 8900000,
    owner: "Energy Holdings Corporation",
    ownerWealth: 485000000,
    type: "property",
    state: "Texas",
    coordinates: { lat: 29.7604, lng: -95.3698 },
  },
  {
    id: "prop_texas_3",
    title: "Austin Tech Estate",
    subtitle: "Silicon Hills Mansion",
    location: "Austin, TX",
    value: 6200000,
    owner: "Texas Technology Ventures",
    ownerWealth: 285000000,
    type: "property",
    state: "Texas",
    coordinates: { lat: 30.2672, lng: -97.7431 },
  },

  // UTAH
  {
    id: "prop_utah_1",
    title: "Park City Ski Estate",
    subtitle: "Wasatch Mountains Mansion",
    location: "Park City, UT",
    value: 8500000,
    owner: "Mountain Resort Holdings",
    ownerWealth: 285000000,
    type: "property",
    state: "Utah",
    coordinates: { lat: 40.6461, lng: -111.498 },
  },
  {
    id: "prop_utah_2",
    title: "Salt Lake City Tech Estate",
    subtitle: "Silicon Slopes Mansion",
    location: "Salt Lake City, UT",
    value: 3200000,
    owner: "Utah Technology Group",
    ownerWealth: 125000000,
    type: "property",
    state: "Utah",
    coordinates: { lat: 40.7608, lng: -111.891 },
  },

  // VERMONT
  {
    id: "prop_vermont_1",
    title: "Stowe Ski Resort Estate",
    subtitle: "Green Mountains Mansion",
    location: "Stowe, VT",
    value: 4800000,
    owner: "Vermont Holdings Trust",
    ownerWealth: 125000000,
    type: "property",
    state: "Vermont",
    coordinates: { lat: 44.4654, lng: -72.6874 },
  },
  {
    id: "prop_vermont_2",
    title: "Burlington Lake Estate",
    subtitle: "Lake Champlain Mansion",
    location: "Burlington, VT",
    value: 2800000,
    owner: "New England Holdings LLC",
    ownerWealth: 85000000,
    type: "property",
    state: "Vermont",
    coordinates: { lat: 44.4759, lng: -73.2121 },
  },

  // VIRGINIA
  {
    id: "prop_virginia_1",
    title: "Virginia Beach Resort Estate",
    subtitle: "Atlantic Coast Mansion",
    location: "Virginia Beach, VA",
    value: 4800000,
    owner: "Coastal Holdings Corporation",
    ownerWealth: 165000000,
    type: "property",
    state: "Virginia",
    coordinates: { lat: 36.8529, lng: -75.978 },
  },
  {
    id: "prop_virginia_2",
    title: "Richmond Historic Estate",
    subtitle: "Monument Avenue Mansion",
    location: "Richmond, VA",
    value: 3200000,
    owner: "Virginia Heritage Holdings",
    ownerWealth: 125000000,
    type: "property",
    state: "Virginia",
    coordinates: { lat: 37.5407, lng: -77.436 },
  },

  // WASHINGTON
  {
    id: "prop_washington_1",
    title: "Seattle Tech Estate",
    subtitle: "Emerald City Mansion",
    location: "Seattle, WA",
    value: 12500000,
    owner: "Pacific Northwest Tech Giant",
    ownerWealth: 2800000000,
    type: "property",
    state: "Washington",
    coordinates: { lat: 47.6062, lng: -122.3321 },
  },
  {
    id: "prop_washington_2",
    title: "Spokane Mining Estate",
    subtitle: "Inland Empire Mansion",
    location: "Spokane, WA",
    value: 2800000,
    owner: "Mining Holdings Group",
    ownerWealth: 125000000,
    type: "property",
    state: "Washington",
    coordinates: { lat: 47.6587, lng: -117.426 },
  },

  // WEST VIRGINIA
  {
    id: "prop_westvirginia_1",
    title: "Charleston Coal Estate",
    subtitle: "Appalachian Mountains Mansion",
    location: "Charleston, WV",
    value: 2200000,
    owner: "Coal Dynasty Holdings",
    ownerWealth: 165000000,
    type: "property",
    state: "West Virginia",
    coordinates: { lat: 38.3498, lng: -81.6326 },
  },
  {
    id: "prop_westvirginia_2",
    title: "Morgantown University Estate",
    subtitle: "Academic District Mansion",
    location: "Morgantown, WV",
    value: 1800000,
    owner: "Educational Holdings Trust",
    ownerWealth: 85000000,
    type: "property",
    state: "West Virginia",
    coordinates: { lat: 39.6295, lng: -79.9553 },
  },

  // WISCONSIN
  {
    id: "prop_wisconsin_1",
    title: "Milwaukee Brewing Estate",
    subtitle: "Beer Capital Mansion",
    location: "Milwaukee, WI",
    value: 3800000,
    owner: "Brewing Dynasty Holdings",
    ownerWealth: 185000000,
    type: "property",
    state: "Wisconsin",
    coordinates: { lat: 43.0389, lng: -87.9065 },
  },
  {
    id: "prop_wisconsin_2",
    title: "Madison University Estate",
    subtitle: "Capitol District Mansion",
    location: "Madison, WI",
    value: 2400000,
    owner: "Academic Holdings Group",
    ownerWealth: 95000000,
    type: "property",
    state: "Wisconsin",
    coordinates: { lat: 43.0731, lng: -89.4012 },
  },

  // WYOMING
  {
    id: "prop_wyoming_1",
    title: "Jackson Hole Ski Estate",
    subtitle: "Teton Range Mansion",
    location: "Jackson Hole, WY",
    value: 18500000,
    owner: "Mountain Holdings Corporation",
    ownerWealth: 650000000,
    type: "property",
    state: "Wyoming",
    coordinates: { lat: 43.4799, lng: -110.7624 },
  },
  {
    id: "prop_wyoming_2",
    title: "Cheyenne Ranch Estate",
    subtitle: "High Plains Mansion",
    location: "Cheyenne, WY",
    value: 2800000,
    owner: "Ranch Holdings LLC",
    ownerWealth: 125000000,
    type: "property",
    state: "Wyoming",
    coordinates: { lat: 41.14, lng: -104.8197 },
  },

  // WASHINGTON DC
  {
    id: "prop_dc_1",
    title: "Georgetown Political Estate",
    subtitle: "Capitol Hill Mansion",
    location: "Washington, DC",
    value: 15800000,
    owner: "Political Dynasty Holdings",
    type: "property",
    state: "District of Columbia",
    coordinates: { lat: 38.9072, lng: -77.0369 },
  },
  {
    id: "prop_dc_2",
    title: "Dupont Circle Embassy Estate",
    subtitle: "Diplomatic District Mansion",
    location: "Washington, DC",
    value: 8900000,
    owner: "International Holdings Group",
    ownerWealth: 285000000,
    type: "property",
    state: "District of Columbia",
    coordinates: { lat: 38.9097, lng: -77.0365 },
  },
]

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)

    const query = searchParams.get("q") || ""
    const type = searchParams.get("type") || "all"
    const minValue = Number.parseInt(searchParams.get("minValue") || "0")
    const maxValue = Number.parseInt(searchParams.get("maxValue") || "50000000")
    const location = searchParams.get("location") || ""

    console.log("🔍 API Search received:", {
      query,
      type,
      minValue,
      maxValue,
      location,
      timestamp: new Date().toISOString(),
    })

    // Filter properties based on search criteria
    const filteredResults = ALL_US_PROPERTIES.filter((property) => {
      // Text search across multiple fields
      const searchText = query.toLowerCase()
      const matchesText =
        !searchText ||
        property.title.toLowerCase().includes(searchText) ||
        property.subtitle.toLowerCase().includes(searchText) ||
        property.location.toLowerCase().includes(searchText) ||
        property.owner.toLowerCase().includes(searchText) ||
        property.state.toLowerCase().includes(searchText)

      // Value range filter
      const matchesValue = property.value >= minValue && property.value <= maxValue

      // Type filter
      const matchesType = type === "all" || property.type === type

      // Location filter
      const matchesLocation =
        !location ||
        property.location.toLowerCase().includes(location.toLowerCase()) ||
        property.state.toLowerCase().includes(location.toLowerCase())

      return matchesText && matchesValue && matchesType && matchesLocation
    })

    // Sort by value (highest first)
    filteredResults.sort((a, b) => b.value - a.value)

    // Generate suggestions based on search
    const suggestions = []
    if (query) {
      const states = [...new Set(ALL_US_PROPERTIES.map((p) => p.state))]
      const matchingStates = states.filter((state) => state.toLowerCase().includes(query.toLowerCase())).slice(0, 3)

      suggestions.push(...matchingStates.map((state) => `Properties in ${state}`))
    }

    const response = {
      query,
      totalResults: filteredResults.length,
      results: filteredResults.slice(0, 20), // Limit to 20 results
      suggestions,
      filters: { type, minValue, maxValue, location },
      states: [...new Set(filteredResults.map((p) => p.state))].slice(0, 10),
    }

    console.log("📊 API Search returning:", {
      query,
      totalResults: response.totalResults,
      resultTypes: [...new Set(response.results.map((r) => r.type))],
      topStates: response.states.slice(0, 5),
      firstResult: response.results[0]?.title || "No results",
    })

    return NextResponse.json(response)
  } catch (error) {
    console.error("❌ Search API error:", error)
    const { searchParams } = new URL(request.url)
    return NextResponse.json(
      {
        error: "Search failed",
        details: error instanceof Error ? error.message : "Unknown error",
        query: searchParams.get("q") || "",
        totalResults: 0,
        results: [],
        suggestions: [],
      },
      { status: 500 },
    )
  }
}
